//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.09 at 10:59:16 AM EST 
//


package org.cvrgrid.hl7aecg.jaxb.beans;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ActClass.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ActClass">
 *   &lt;restriction base="{urn:hl7-org:v3}cs">
 *     &lt;enumeration value="ACT"/>
 *     &lt;enumeration value="CNTRCT"/>
 *     &lt;enumeration value="FCNTRCT"/>
 *     &lt;enumeration value="COV"/>
 *     &lt;enumeration value="CACT"/>
 *     &lt;enumeration value="ACTN"/>
 *     &lt;enumeration value="INFO"/>
 *     &lt;enumeration value="STC"/>
 *     &lt;enumeration value="OBS"/>
 *     &lt;enumeration value="OBSSER"/>
 *     &lt;enumeration value="OBSCOR"/>
 *     &lt;enumeration value="CASE"/>
 *     &lt;enumeration value="OUTB"/>
 *     &lt;enumeration value="ROIBND"/>
 *     &lt;enumeration value="ROIOVL"/>
 *     &lt;enumeration value="ALRT"/>
 *     &lt;enumeration value="CLNTRL"/>
 *     &lt;enumeration value="CNOD"/>
 *     &lt;enumeration value="COND"/>
 *     &lt;enumeration value="DGIMG"/>
 *     &lt;enumeration value="MPROT"/>
 *     &lt;enumeration value="SPCOBS"/>
 *     &lt;enumeration value="SPLY"/>
 *     &lt;enumeration value="DIET"/>
 *     &lt;enumeration value="DOC"/>
 *     &lt;enumeration value="DOCCLIN"/>
 *     &lt;enumeration value="CDALVLONE"/>
 *     &lt;enumeration value="DOCLIST"/>
 *     &lt;enumeration value="ordered"/>
 *     &lt;enumeration value="unordered"/>
 *     &lt;enumeration value="TBLDATA"/>
 *     &lt;enumeration value="TBLHDR"/>
 *     &lt;enumeration value="TBLCOL"/>
 *     &lt;enumeration value="TBLCOLGP"/>
 *     &lt;enumeration value="tbody"/>
 *     &lt;enumeration value="tfoot"/>
 *     &lt;enumeration value="thead"/>
 *     &lt;enumeration value="TBLROW"/>
 *     &lt;enumeration value="DOCBODY"/>
 *     &lt;enumeration value="DOCCNTNT"/>
 *     &lt;enumeration value="DOCLSTITM"/>
 *     &lt;enumeration value="DOCPARA"/>
 *     &lt;enumeration value="DOCSECT"/>
 *     &lt;enumeration value="DOCTBL"/>
 *     &lt;enumeration value="LINKHTML"/>
 *     &lt;enumeration value="LOCALATTR"/>
 *     &lt;enumeration value="LOCALMRKP"/>
 *     &lt;enumeration value="ACCM"/>
 *     &lt;enumeration value="ACCT"/>
 *     &lt;enumeration value="ACSN"/>
 *     &lt;enumeration value="ADJUD"/>
 *     &lt;enumeration value="CONS"/>
 *     &lt;enumeration value="CONTREG"/>
 *     &lt;enumeration value="CTTEVENT"/>
 *     &lt;enumeration value="ENC"/>
 *     &lt;enumeration value="INC"/>
 *     &lt;enumeration value="INFRM"/>
 *     &lt;enumeration value="INVE"/>
 *     &lt;enumeration value="LIST"/>
 *     &lt;enumeration value="PCPR"/>
 *     &lt;enumeration value="PROC"/>
 *     &lt;enumeration value="REFR"/>
 *     &lt;enumeration value="REG"/>
 *     &lt;enumeration value="SBADM"/>
 *     &lt;enumeration value="SPCTRT"/>
 *     &lt;enumeration value="TRNS"/>
 *     &lt;enumeration value="XACT"/>
 *     &lt;enumeration value="IDREF"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ActClass")
@XmlEnum
public enum ActClass {

    ACT("ACT"),
    CNTRCT("CNTRCT"),
    FCNTRCT("FCNTRCT"),
    COV("COV"),
    CACT("CACT"),
    ACTN("ACTN"),
    INFO("INFO"),
    STC("STC"),
    OBS("OBS"),
    OBSSER("OBSSER"),
    OBSCOR("OBSCOR"),
    CASE("CASE"),
    OUTB("OUTB"),
    ROIBND("ROIBND"),
    ROIOVL("ROIOVL"),
    ALRT("ALRT"),
    CLNTRL("CLNTRL"),
    CNOD("CNOD"),
    COND("COND"),
    DGIMG("DGIMG"),
    MPROT("MPROT"),
    SPCOBS("SPCOBS"),
    SPLY("SPLY"),
    DIET("DIET"),
    DOC("DOC"),
    DOCCLIN("DOCCLIN"),
    CDALVLONE("CDALVLONE"),
    DOCLIST("DOCLIST"),
    @XmlEnumValue("ordered")
    ORDERED("ordered"),
    @XmlEnumValue("unordered")
    UNORDERED("unordered"),
    TBLDATA("TBLDATA"),
    TBLHDR("TBLHDR"),
    TBLCOL("TBLCOL"),
    TBLCOLGP("TBLCOLGP"),
    @XmlEnumValue("tbody")
    TBODY("tbody"),
    @XmlEnumValue("tfoot")
    TFOOT("tfoot"),
    @XmlEnumValue("thead")
    THEAD("thead"),
    TBLROW("TBLROW"),
    DOCBODY("DOCBODY"),
    DOCCNTNT("DOCCNTNT"),
    DOCLSTITM("DOCLSTITM"),
    DOCPARA("DOCPARA"),
    DOCSECT("DOCSECT"),
    DOCTBL("DOCTBL"),
    LINKHTML("LINKHTML"),
    LOCALATTR("LOCALATTR"),
    LOCALMRKP("LOCALMRKP"),
    ACCM("ACCM"),
    ACCT("ACCT"),
    ACSN("ACSN"),
    ADJUD("ADJUD"),
    CONS("CONS"),
    CONTREG("CONTREG"),
    CTTEVENT("CTTEVENT"),
    ENC("ENC"),
    INC("INC"),
    INFRM("INFRM"),
    INVE("INVE"),
    LIST("LIST"),
    PCPR("PCPR"),
    PROC("PROC"),
    REFR("REFR"),
    REG("REG"),
    SBADM("SBADM"),
    SPCTRT("SPCTRT"),
    TRNS("TRNS"),
    XACT("XACT"),
    IDREF("IDREF");
    private final String value;

    ActClass(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ActClass fromValue(String v) {
        for (ActClass c: ActClass.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
