//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.09 at 10:59:16 AM EST 
//


package org.cvrgrid.hl7aecg.jaxb.beans;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ActClassObservation.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ActClassObservation">
 *   &lt;restriction base="{urn:hl7-org:v3}ActClass">
 *     &lt;enumeration value="OBSSER"/>
 *     &lt;enumeration value="OBSCOR"/>
 *     &lt;enumeration value="CASE"/>
 *     &lt;enumeration value="OUTB"/>
 *     &lt;enumeration value="ROIBND"/>
 *     &lt;enumeration value="ROIOVL"/>
 *     &lt;enumeration value="ALRT"/>
 *     &lt;enumeration value="CLNTRL"/>
 *     &lt;enumeration value="CNOD"/>
 *     &lt;enumeration value="COND"/>
 *     &lt;enumeration value="DGIMG"/>
 *     &lt;enumeration value="MPROT"/>
 *     &lt;enumeration value="SPCOBS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ActClassObservation")
@XmlEnum(ActClass.class)
public enum ActClassObservation {

    OBSSER,
    OBSCOR,
    CASE,
    OUTB,
    ROIBND,
    ROIOVL,
    ALRT,
    CLNTRL,
    CNOD,
    COND,
    DGIMG,
    MPROT,
    SPCOBS;

    public String value() {
        return name();
    }

    public static ActClassObservation fromValue(String v) {
        return valueOf(v);
    }

}
