//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.09 at 10:59:16 AM EST 
//


package org.cvrgrid.hl7aecg.jaxb.beans;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ActMood.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ActMood">
 *   &lt;restriction base="{urn:hl7-org:v3}cs">
 *     &lt;enumeration value="DEF"/>
 *     &lt;enumeration value="EVN.CRT"/>
 *     &lt;enumeration value="OPT"/>
 *     &lt;enumeration value="GOL"/>
 *     &lt;enumeration value="INT"/>
 *     &lt;enumeration value="PRP"/>
 *     &lt;enumeration value="APT"/>
 *     &lt;enumeration value="ARQ"/>
 *     &lt;enumeration value="SLOT"/>
 *     &lt;enumeration value="PRMS"/>
 *     &lt;enumeration value="EVN"/>
 *     &lt;enumeration value="RQO"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ActMood")
@XmlEnum
public enum ActMood {

    DEF("DEF"),
    @XmlEnumValue("EVN.CRT")
    EVN_CRT("EVN.CRT"),
    OPT("OPT"),
    GOL("GOL"),
    INT("INT"),
    PRP("PRP"),
    APT("APT"),
    ARQ("ARQ"),
    SLOT("SLOT"),
    PRMS("PRMS"),
    EVN("EVN"),
    RQO("RQO");
    private final String value;

    ActMood(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ActMood fromValue(String v) {
        for (ActMood c: ActMood.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
