//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.09 at 10:59:16 AM EST 
//


package org.cvrgrid.hl7aecg.jaxb.beans;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ActRelationshipPertains.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ActRelationshipPertains">
 *   &lt;restriction base="{urn:hl7-org:v3}ActRelationshipType">
 *     &lt;enumeration value="CHRG"/>
 *     &lt;enumeration value="COST"/>
 *     &lt;enumeration value="CREDIT"/>
 *     &lt;enumeration value="DEBIT"/>
 *     &lt;enumeration value="SPRT"/>
 *     &lt;enumeration value="SPRTBND"/>
 *     &lt;enumeration value="AUTH"/>
 *     &lt;enumeration value="CAUS"/>
 *     &lt;enumeration value="COVBY"/>
 *     &lt;enumeration value="DRIV"/>
 *     &lt;enumeration value="EXPL"/>
 *     &lt;enumeration value="LIMIT"/>
 *     &lt;enumeration value="MFST"/>
 *     &lt;enumeration value="NAME"/>
 *     &lt;enumeration value="PREV"/>
 *     &lt;enumeration value="REFR"/>
 *     &lt;enumeration value="REFV"/>
 *     &lt;enumeration value="SUBJ"/>
 *     &lt;enumeration value="SUMM"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ActRelationshipPertains")
@XmlEnum(ActRelationshipType.class)
public enum ActRelationshipPertains {

    CHRG,
    COST,
    CREDIT,
    DEBIT,
    SPRT,
    SPRTBND,
    AUTH,
    CAUS,
    COVBY,
    DRIV,
    EXPL,
    LIMIT,
    MFST,
    NAME,
    PREV,
    REFR,
    REFV,
    SUBJ,
    SUMM;

    public String value() {
        return name();
    }

    public static ActRelationshipPertains fromValue(String v) {
        return valueOf(v);
    }

}
