//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.09 at 10:59:16 AM EST 
//


package org.cvrgrid.hl7aecg.jaxb.beans;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			Mailing and home or office addresses. A sequence of address parts,
 * 			such as street or post office Box, city, postal code, country, etc.
 * 			
 * 
 * <p>Java class for AD complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AD">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="delimiter">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{urn:hl7-org:v3}ADXP">
 *                   &lt;attribute name="partType" type="{urn:hl7-org:v3}cs_AddressPartType" fixed="DEL" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="country">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{urn:hl7-org:v3}ADXP">
 *                   &lt;attribute name="partType" type="{urn:hl7-org:v3}cs_AddressPartType" fixed="CNT" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="state">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{urn:hl7-org:v3}ADXP">
 *                   &lt;attribute name="partType" type="{urn:hl7-org:v3}cs_AddressPartType" fixed="STA" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="county">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{urn:hl7-org:v3}ADXP">
 *                   &lt;attribute name="partType" type="{urn:hl7-org:v3}cs_AddressPartType" fixed="CPA" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="city">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{urn:hl7-org:v3}ADXP">
 *                   &lt;attribute name="partType" type="{urn:hl7-org:v3}cs_AddressPartType" fixed="CTY" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="postalCode">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{urn:hl7-org:v3}ADXP">
 *                   &lt;attribute name="partType" type="{urn:hl7-org:v3}cs_AddressPartType" fixed="ZIP" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="streetAddressLine">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{urn:hl7-org:v3}ADXP">
 *                   &lt;attribute name="partType" type="{urn:hl7-org:v3}cs_AddressPartType" fixed="SAL" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="streetName">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{urn:hl7-org:v3}ADXP">
 *                   &lt;attribute name="partType" type="{urn:hl7-org:v3}cs_AddressPartType" fixed="STR" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="houseNumber">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{urn:hl7-org:v3}ADXP">
 *                   &lt;attribute name="partType" type="{urn:hl7-org:v3}cs_AddressPartType" fixed="HNR" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="direction">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{urn:hl7-org:v3}ADXP">
 *                   &lt;attribute name="partType" type="{urn:hl7-org:v3}cs_AddressPartType" fixed="DIR" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="additionalLocator">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{urn:hl7-org:v3}ADXP">
 *                   &lt;attribute name="partType" type="{urn:hl7-org:v3}cs_AddressPartType" fixed="ADL" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="postBox">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{urn:hl7-org:v3}ADXP">
 *                   &lt;attribute name="partType" type="{urn:hl7-org:v3}cs_AddressPartType" fixed="POB" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="censusTract">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{urn:hl7-org:v3}ADXP">
 *                   &lt;attribute name="partType" type="{urn:hl7-org:v3}cs_AddressPartType" fixed="CEN" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element name="validTime" type="{urn:hl7-org:v3}SXCM_TS" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:hl7-org:v3}ANY"/>
 *       &lt;attribute name="use" type="{urn:hl7-org:v3}set_cs_PostalAddressUse" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AD", propOrder = {
    "content"
})
public class AD {

    @XmlElementRefs({
        @XmlElementRef(name = "postalCode", namespace = "urn:hl7-org:v3", type = JAXBElement.class),
        @XmlElementRef(name = "houseNumber", namespace = "urn:hl7-org:v3", type = JAXBElement.class),
        @XmlElementRef(name = "streetName", namespace = "urn:hl7-org:v3", type = JAXBElement.class),
        @XmlElementRef(name = "streetAddressLine", namespace = "urn:hl7-org:v3", type = JAXBElement.class),
        @XmlElementRef(name = "city", namespace = "urn:hl7-org:v3", type = JAXBElement.class),
        @XmlElementRef(name = "county", namespace = "urn:hl7-org:v3", type = JAXBElement.class),
        @XmlElementRef(name = "postBox", namespace = "urn:hl7-org:v3", type = JAXBElement.class),
        @XmlElementRef(name = "censusTract", namespace = "urn:hl7-org:v3", type = JAXBElement.class),
        @XmlElementRef(name = "state", namespace = "urn:hl7-org:v3", type = JAXBElement.class),
        @XmlElementRef(name = "additionalLocator", namespace = "urn:hl7-org:v3", type = JAXBElement.class),
        @XmlElementRef(name = "country", namespace = "urn:hl7-org:v3", type = JAXBElement.class),
        @XmlElementRef(name = "delimiter", namespace = "urn:hl7-org:v3", type = JAXBElement.class),
        @XmlElementRef(name = "validTime", namespace = "urn:hl7-org:v3", type = JAXBElement.class),
        @XmlElementRef(name = "direction", namespace = "urn:hl7-org:v3", type = JAXBElement.class)
    })
    @XmlMixed
    protected List<Serializable> content;
    @XmlAttribute(name = "use")
    protected List<CsPostalAddressUse> use;
    @XmlAttribute(name = "nullFlavor")
    protected CsNullFlavor nullFlavor;

    /**
     * 
     * 			Mailing and home or office addresses. A sequence of address parts,
     * 			such as street or post office Box, city, postal code, country, etc.
     * 			Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link AD.PostalCode }{@code >}
     * {@link JAXBElement }{@code <}{@link AD.County }{@code >}
     * {@link JAXBElement }{@code <}{@link AD.PostBox }{@code >}
     * {@link JAXBElement }{@code <}{@link AD.AdditionalLocator }{@code >}
     * {@link JAXBElement }{@code <}{@link AD.Country }{@code >}
     * {@link JAXBElement }{@code <}{@link AD.Delimiter }{@code >}
     * {@link JAXBElement }{@code <}{@link AD.HouseNumber }{@code >}
     * {@link String }
     * {@link JAXBElement }{@code <}{@link AD.StreetName }{@code >}
     * {@link JAXBElement }{@code <}{@link AD.StreetAddressLine }{@code >}
     * {@link JAXBElement }{@code <}{@link AD.City }{@code >}
     * {@link JAXBElement }{@code <}{@link AD.CensusTract }{@code >}
     * {@link JAXBElement }{@code <}{@link AD.State }{@code >}
     * {@link JAXBElement }{@code <}{@link SXCMTS }{@code >}
     * {@link JAXBElement }{@code <}{@link AD.Direction }{@code >}
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

    /**
     * Gets the value of the use property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the use property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CsPostalAddressUse }
     * 
     * 
     */
    public List<CsPostalAddressUse> getUse() {
        if (use == null) {
            use = new ArrayList<CsPostalAddressUse>();
        }
        return this.use;
    }

    /**
     * Gets the value of the nullFlavor property.
     * 
     * @return
     *     possible object is
     *     {@link CsNullFlavor }
     *     
     */
    public CsNullFlavor getNullFlavor() {
        return nullFlavor;
    }

    /**
     * Sets the value of the nullFlavor property.
     * 
     * @param value
     *     allowed object is
     *     {@link CsNullFlavor }
     *     
     */
    public void setNullFlavor(CsNullFlavor value) {
        this.nullFlavor = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{urn:hl7-org:v3}ADXP">
     *       &lt;attribute name="partType" type="{urn:hl7-org:v3}cs_AddressPartType" fixed="ADL" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class AdditionalLocator
        extends ADXP
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{urn:hl7-org:v3}ADXP">
     *       &lt;attribute name="partType" type="{urn:hl7-org:v3}cs_AddressPartType" fixed="CEN" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class CensusTract
        extends ADXP
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{urn:hl7-org:v3}ADXP">
     *       &lt;attribute name="partType" type="{urn:hl7-org:v3}cs_AddressPartType" fixed="CTY" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class City
        extends ADXP
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{urn:hl7-org:v3}ADXP">
     *       &lt;attribute name="partType" type="{urn:hl7-org:v3}cs_AddressPartType" fixed="CNT" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Country
        extends ADXP
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{urn:hl7-org:v3}ADXP">
     *       &lt;attribute name="partType" type="{urn:hl7-org:v3}cs_AddressPartType" fixed="CPA" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class County
        extends ADXP
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{urn:hl7-org:v3}ADXP">
     *       &lt;attribute name="partType" type="{urn:hl7-org:v3}cs_AddressPartType" fixed="DEL" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Delimiter
        extends ADXP
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{urn:hl7-org:v3}ADXP">
     *       &lt;attribute name="partType" type="{urn:hl7-org:v3}cs_AddressPartType" fixed="DIR" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Direction
        extends ADXP
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{urn:hl7-org:v3}ADXP">
     *       &lt;attribute name="partType" type="{urn:hl7-org:v3}cs_AddressPartType" fixed="HNR" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class HouseNumber
        extends ADXP
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{urn:hl7-org:v3}ADXP">
     *       &lt;attribute name="partType" type="{urn:hl7-org:v3}cs_AddressPartType" fixed="POB" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PostBox
        extends ADXP
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{urn:hl7-org:v3}ADXP">
     *       &lt;attribute name="partType" type="{urn:hl7-org:v3}cs_AddressPartType" fixed="ZIP" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PostalCode
        extends ADXP
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{urn:hl7-org:v3}ADXP">
     *       &lt;attribute name="partType" type="{urn:hl7-org:v3}cs_AddressPartType" fixed="STA" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class State
        extends ADXP
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{urn:hl7-org:v3}ADXP">
     *       &lt;attribute name="partType" type="{urn:hl7-org:v3}cs_AddressPartType" fixed="SAL" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class StreetAddressLine
        extends ADXP
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{urn:hl7-org:v3}ADXP">
     *       &lt;attribute name="partType" type="{urn:hl7-org:v3}cs_AddressPartType" fixed="STR" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class StreetName
        extends ADXP
    {


    }

}
