//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.09 at 10:59:16 AM EST 
//


package org.cvrgrid.hl7aecg.jaxb.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				2003-10-02: pvb: see xs:annotation/xs:documentation for ED, EC and SC...
 * 			
 * 
 * <p>Java class for ADXP complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ADXP">
 *   &lt;complexContent>
 *     &lt;restriction base="{urn:hl7-org:v3}EAXP">
 *       &lt;attribute name="mediaType" type="{urn:hl7-org:v3}cs" fixed="text/plain" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ADXP")
@XmlSeeAlso({
    org.cvrgrid.hl7aecg.jaxb.beans.AD.Delimiter.class,
    org.cvrgrid.hl7aecg.jaxb.beans.AD.Country.class,
    org.cvrgrid.hl7aecg.jaxb.beans.AD.State.class,
    org.cvrgrid.hl7aecg.jaxb.beans.AD.County.class,
    org.cvrgrid.hl7aecg.jaxb.beans.AD.City.class,
    org.cvrgrid.hl7aecg.jaxb.beans.AD.PostalCode.class,
    org.cvrgrid.hl7aecg.jaxb.beans.AD.StreetAddressLine.class,
    org.cvrgrid.hl7aecg.jaxb.beans.AD.StreetName.class,
    org.cvrgrid.hl7aecg.jaxb.beans.AD.HouseNumber.class,
    org.cvrgrid.hl7aecg.jaxb.beans.AD.Direction.class,
    org.cvrgrid.hl7aecg.jaxb.beans.AD.AdditionalLocator.class,
    org.cvrgrid.hl7aecg.jaxb.beans.AD.PostBox.class,
    org.cvrgrid.hl7aecg.jaxb.beans.AD.CensusTract.class
})
public class ADXP
    extends EAXP
{


}
