//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.09 at 10:59:16 AM EST 
//


package org.cvrgrid.hl7aecg.jaxb.beans;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Associations.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Associations">
 *   &lt;restriction base="{urn:hl7-org:v3}cs">
 *     &lt;enumeration value="outboundRelationship"/>
 *     &lt;enumeration value="inboundRelationship"/>
 *     &lt;enumeration value="languageCommunication"/>
 *     &lt;enumeration value="playedRole"/>
 *     &lt;enumeration value="scopedRole"/>
 *     &lt;enumeration value="act"/>
 *     &lt;enumeration value="role"/>
 *     &lt;enumeration value="player"/>
 *     &lt;enumeration value="scoper"/>
 *     &lt;enumeration value="participation"/>
 *     &lt;enumeration value="outboundLink"/>
 *     &lt;enumeration value="inboundLink"/>
 *     &lt;enumeration value="source"/>
 *     &lt;enumeration value="target"/>
 *     &lt;enumeration value="acknowledges"/>
 *     &lt;enumeration value="conveyingMessage"/>
 *     &lt;enumeration value="annotatedBy"/>
 *     &lt;enumeration value="acknowledgement"/>
 *     &lt;enumeration value="entity"/>
 *     &lt;enumeration value="transmission"/>
 *     &lt;enumeration value="payload"/>
 *     &lt;enumeration value="queryEvent"/>
 *     &lt;enumeration value="userAsLeft"/>
 *     &lt;enumeration value="userAsRight"/>
 *     &lt;enumeration value="acknowledgedBy"/>
 *     &lt;enumeration value="conveyedAcknowledgement"/>
 *     &lt;enumeration value="queryByParameter"/>
 *     &lt;enumeration value="parameterList"/>
 *     &lt;enumeration value="parameter"/>
 *     &lt;enumeration value="selectionExpression"/>
 *     &lt;enumeration value="controlAct"/>
 *     &lt;enumeration value="sortControl"/>
 *     &lt;enumeration value="leftSide"/>
 *     &lt;enumeration value="queryBySelection"/>
 *     &lt;enumeration value="rightSide"/>
 *     &lt;enumeration value="querySpec"/>
 *     &lt;enumeration value="communicationFunction"/>
 *     &lt;enumeration value="attentionLine"/>
 *     &lt;enumeration value="batch"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Associations")
@XmlEnum
public enum Associations {

    @XmlEnumValue("outboundRelationship")
    OUTBOUND_RELATIONSHIP("outboundRelationship"),
    @XmlEnumValue("inboundRelationship")
    INBOUND_RELATIONSHIP("inboundRelationship"),
    @XmlEnumValue("languageCommunication")
    LANGUAGE_COMMUNICATION("languageCommunication"),
    @XmlEnumValue("playedRole")
    PLAYED_ROLE("playedRole"),
    @XmlEnumValue("scopedRole")
    SCOPED_ROLE("scopedRole"),
    @XmlEnumValue("act")
    ACT("act"),
    @XmlEnumValue("role")
    ROLE("role"),
    @XmlEnumValue("player")
    PLAYER("player"),
    @XmlEnumValue("scoper")
    SCOPER("scoper"),
    @XmlEnumValue("participation")
    PARTICIPATION("participation"),
    @XmlEnumValue("outboundLink")
    OUTBOUND_LINK("outboundLink"),
    @XmlEnumValue("inboundLink")
    INBOUND_LINK("inboundLink"),
    @XmlEnumValue("source")
    SOURCE("source"),
    @XmlEnumValue("target")
    TARGET("target"),
    @XmlEnumValue("acknowledges")
    ACKNOWLEDGES("acknowledges"),
    @XmlEnumValue("conveyingMessage")
    CONVEYING_MESSAGE("conveyingMessage"),
    @XmlEnumValue("annotatedBy")
    ANNOTATED_BY("annotatedBy"),
    @XmlEnumValue("acknowledgement")
    ACKNOWLEDGEMENT("acknowledgement"),
    @XmlEnumValue("entity")
    ENTITY("entity"),
    @XmlEnumValue("transmission")
    TRANSMISSION("transmission"),
    @XmlEnumValue("payload")
    PAYLOAD("payload"),
    @XmlEnumValue("queryEvent")
    QUERY_EVENT("queryEvent"),
    @XmlEnumValue("userAsLeft")
    USER_AS_LEFT("userAsLeft"),
    @XmlEnumValue("userAsRight")
    USER_AS_RIGHT("userAsRight"),
    @XmlEnumValue("acknowledgedBy")
    ACKNOWLEDGED_BY("acknowledgedBy"),
    @XmlEnumValue("conveyedAcknowledgement")
    CONVEYED_ACKNOWLEDGEMENT("conveyedAcknowledgement"),
    @XmlEnumValue("queryByParameter")
    QUERY_BY_PARAMETER("queryByParameter"),
    @XmlEnumValue("parameterList")
    PARAMETER_LIST("parameterList"),
    @XmlEnumValue("parameter")
    PARAMETER("parameter"),
    @XmlEnumValue("selectionExpression")
    SELECTION_EXPRESSION("selectionExpression"),
    @XmlEnumValue("controlAct")
    CONTROL_ACT("controlAct"),
    @XmlEnumValue("sortControl")
    SORT_CONTROL("sortControl"),
    @XmlEnumValue("leftSide")
    LEFT_SIDE("leftSide"),
    @XmlEnumValue("queryBySelection")
    QUERY_BY_SELECTION("queryBySelection"),
    @XmlEnumValue("rightSide")
    RIGHT_SIDE("rightSide"),
    @XmlEnumValue("querySpec")
    QUERY_SPEC("querySpec"),
    @XmlEnumValue("communicationFunction")
    COMMUNICATION_FUNCTION("communicationFunction"),
    @XmlEnumValue("attentionLine")
    ATTENTION_LINE("attentionLine"),
    @XmlEnumValue("batch")
    BATCH("batch");
    private final String value;

    Associations(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Associations fromValue(String v) {
        for (Associations c: Associations.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
