//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.09 at 10:59:16 AM EST 
//


package org.cvrgrid.hl7aecg.jaxb.beans;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Classes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Classes">
 *   &lt;restriction base="{urn:hl7-org:v3}cs">
 *     &lt;enumeration value="Access"/>
 *     &lt;enumeration value="Account"/>
 *     &lt;enumeration value="AcknowledgementDetail"/>
 *     &lt;enumeration value="Act"/>
 *     &lt;enumeration value="ActHeir"/>
 *     &lt;enumeration value="ActRelationship"/>
 *     &lt;enumeration value="Container"/>
 *     &lt;enumeration value="Device"/>
 *     &lt;enumeration value="DeviceTask"/>
 *     &lt;enumeration value="DiagnosticImage"/>
 *     &lt;enumeration value="Diet"/>
 *     &lt;enumeration value="Employee"/>
 *     &lt;enumeration value="Entity"/>
 *     &lt;enumeration value="EntityHeir"/>
 *     &lt;enumeration value="FinancialContract"/>
 *     &lt;enumeration value="FinancialTransaction"/>
 *     &lt;enumeration value="InvoiceElement"/>
 *     &lt;enumeration value="LanguageCommunication"/>
 *     &lt;enumeration value="LicensedEntity"/>
 *     &lt;enumeration value="LivingSubject"/>
 *     &lt;enumeration value="ManagedParticipation"/>
 *     &lt;enumeration value="ManufacturedMaterial"/>
 *     &lt;enumeration value="Material"/>
 *     &lt;enumeration value="NonPersonLivingSubject"/>
 *     &lt;enumeration value="Observation"/>
 *     &lt;enumeration value="Organization"/>
 *     &lt;enumeration value="Participation"/>
 *     &lt;enumeration value="Patient"/>
 *     &lt;enumeration value="PatientEncounter"/>
 *     &lt;enumeration value="Person"/>
 *     &lt;enumeration value="Place"/>
 *     &lt;enumeration value="Procedure"/>
 *     &lt;enumeration value="PublicHealthCase"/>
 *     &lt;enumeration value="Role"/>
 *     &lt;enumeration value="RoleHeir"/>
 *     &lt;enumeration value="RoleLink"/>
 *     &lt;enumeration value="SchedulableResource"/>
 *     &lt;enumeration value="SubstanceAdministration"/>
 *     &lt;enumeration value="Supply"/>
 *     &lt;enumeration value="WorkingList"/>
 *     &lt;enumeration value="Acknowledgement"/>
 *     &lt;enumeration value="AcknowledgementMessage"/>
 *     &lt;enumeration value="AttentionLine"/>
 *     &lt;enumeration value="Batch"/>
 *     &lt;enumeration value="CommunicationFunction"/>
 *     &lt;enumeration value="ContextStructure"/>
 *     &lt;enumeration value="ControlAct"/>
 *     &lt;enumeration value="Document"/>
 *     &lt;enumeration value="InfrastructureRoot"/>
 *     &lt;enumeration value="LinkHtml"/>
 *     &lt;enumeration value="LocalAttr"/>
 *     &lt;enumeration value="LocalMarkup"/>
 *     &lt;enumeration value="LogicalExpression"/>
 *     &lt;enumeration value="Message"/>
 *     &lt;enumeration value="Parameter"/>
 *     &lt;enumeration value="ParameterItem"/>
 *     &lt;enumeration value="ParameterList"/>
 *     &lt;enumeration value="QueryAck"/>
 *     &lt;enumeration value="QueryByParameter"/>
 *     &lt;enumeration value="QueryBySelection"/>
 *     &lt;enumeration value="QueryContinuation"/>
 *     &lt;enumeration value="QueryEvent"/>
 *     &lt;enumeration value="QuerySpec"/>
 *     &lt;enumeration value="RelationalExpression"/>
 *     &lt;enumeration value="SelectionExpression"/>
 *     &lt;enumeration value="SortControl"/>
 *     &lt;enumeration value="Table"/>
 *     &lt;enumeration value="TableCell"/>
 *     &lt;enumeration value="TableColumnStructure"/>
 *     &lt;enumeration value="TableStructure"/>
 *     &lt;enumeration value="Transmission"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Classes")
@XmlEnum
public enum Classes {

    @XmlEnumValue("Access")
    ACCESS("Access"),
    @XmlEnumValue("Account")
    ACCOUNT("Account"),
    @XmlEnumValue("AcknowledgementDetail")
    ACKNOWLEDGEMENT_DETAIL("AcknowledgementDetail"),
    @XmlEnumValue("Act")
    ACT("Act"),
    @XmlEnumValue("ActHeir")
    ACT_HEIR("ActHeir"),
    @XmlEnumValue("ActRelationship")
    ACT_RELATIONSHIP("ActRelationship"),
    @XmlEnumValue("Container")
    CONTAINER("Container"),
    @XmlEnumValue("Device")
    DEVICE("Device"),
    @XmlEnumValue("DeviceTask")
    DEVICE_TASK("DeviceTask"),
    @XmlEnumValue("DiagnosticImage")
    DIAGNOSTIC_IMAGE("DiagnosticImage"),
    @XmlEnumValue("Diet")
    DIET("Diet"),
    @XmlEnumValue("Employee")
    EMPLOYEE("Employee"),
    @XmlEnumValue("Entity")
    ENTITY("Entity"),
    @XmlEnumValue("EntityHeir")
    ENTITY_HEIR("EntityHeir"),
    @XmlEnumValue("FinancialContract")
    FINANCIAL_CONTRACT("FinancialContract"),
    @XmlEnumValue("FinancialTransaction")
    FINANCIAL_TRANSACTION("FinancialTransaction"),
    @XmlEnumValue("InvoiceElement")
    INVOICE_ELEMENT("InvoiceElement"),
    @XmlEnumValue("LanguageCommunication")
    LANGUAGE_COMMUNICATION("LanguageCommunication"),
    @XmlEnumValue("LicensedEntity")
    LICENSED_ENTITY("LicensedEntity"),
    @XmlEnumValue("LivingSubject")
    LIVING_SUBJECT("LivingSubject"),
    @XmlEnumValue("ManagedParticipation")
    MANAGED_PARTICIPATION("ManagedParticipation"),
    @XmlEnumValue("ManufacturedMaterial")
    MANUFACTURED_MATERIAL("ManufacturedMaterial"),
    @XmlEnumValue("Material")
    MATERIAL("Material"),
    @XmlEnumValue("NonPersonLivingSubject")
    NON_PERSON_LIVING_SUBJECT("NonPersonLivingSubject"),
    @XmlEnumValue("Observation")
    OBSERVATION("Observation"),
    @XmlEnumValue("Organization")
    ORGANIZATION("Organization"),
    @XmlEnumValue("Participation")
    PARTICIPATION("Participation"),
    @XmlEnumValue("Patient")
    PATIENT("Patient"),
    @XmlEnumValue("PatientEncounter")
    PATIENT_ENCOUNTER("PatientEncounter"),
    @XmlEnumValue("Person")
    PERSON("Person"),
    @XmlEnumValue("Place")
    PLACE("Place"),
    @XmlEnumValue("Procedure")
    PROCEDURE("Procedure"),
    @XmlEnumValue("PublicHealthCase")
    PUBLIC_HEALTH_CASE("PublicHealthCase"),
    @XmlEnumValue("Role")
    ROLE("Role"),
    @XmlEnumValue("RoleHeir")
    ROLE_HEIR("RoleHeir"),
    @XmlEnumValue("RoleLink")
    ROLE_LINK("RoleLink"),
    @XmlEnumValue("SchedulableResource")
    SCHEDULABLE_RESOURCE("SchedulableResource"),
    @XmlEnumValue("SubstanceAdministration")
    SUBSTANCE_ADMINISTRATION("SubstanceAdministration"),
    @XmlEnumValue("Supply")
    SUPPLY("Supply"),
    @XmlEnumValue("WorkingList")
    WORKING_LIST("WorkingList"),
    @XmlEnumValue("Acknowledgement")
    ACKNOWLEDGEMENT("Acknowledgement"),
    @XmlEnumValue("AcknowledgementMessage")
    ACKNOWLEDGEMENT_MESSAGE("AcknowledgementMessage"),
    @XmlEnumValue("AttentionLine")
    ATTENTION_LINE("AttentionLine"),
    @XmlEnumValue("Batch")
    BATCH("Batch"),
    @XmlEnumValue("CommunicationFunction")
    COMMUNICATION_FUNCTION("CommunicationFunction"),
    @XmlEnumValue("ContextStructure")
    CONTEXT_STRUCTURE("ContextStructure"),
    @XmlEnumValue("ControlAct")
    CONTROL_ACT("ControlAct"),
    @XmlEnumValue("Document")
    DOCUMENT("Document"),
    @XmlEnumValue("InfrastructureRoot")
    INFRASTRUCTURE_ROOT("InfrastructureRoot"),
    @XmlEnumValue("LinkHtml")
    LINK_HTML("LinkHtml"),
    @XmlEnumValue("LocalAttr")
    LOCAL_ATTR("LocalAttr"),
    @XmlEnumValue("LocalMarkup")
    LOCAL_MARKUP("LocalMarkup"),
    @XmlEnumValue("LogicalExpression")
    LOGICAL_EXPRESSION("LogicalExpression"),
    @XmlEnumValue("Message")
    MESSAGE("Message"),
    @XmlEnumValue("Parameter")
    PARAMETER("Parameter"),
    @XmlEnumValue("ParameterItem")
    PARAMETER_ITEM("ParameterItem"),
    @XmlEnumValue("ParameterList")
    PARAMETER_LIST("ParameterList"),
    @XmlEnumValue("QueryAck")
    QUERY_ACK("QueryAck"),
    @XmlEnumValue("QueryByParameter")
    QUERY_BY_PARAMETER("QueryByParameter"),
    @XmlEnumValue("QueryBySelection")
    QUERY_BY_SELECTION("QueryBySelection"),
    @XmlEnumValue("QueryContinuation")
    QUERY_CONTINUATION("QueryContinuation"),
    @XmlEnumValue("QueryEvent")
    QUERY_EVENT("QueryEvent"),
    @XmlEnumValue("QuerySpec")
    QUERY_SPEC("QuerySpec"),
    @XmlEnumValue("RelationalExpression")
    RELATIONAL_EXPRESSION("RelationalExpression"),
    @XmlEnumValue("SelectionExpression")
    SELECTION_EXPRESSION("SelectionExpression"),
    @XmlEnumValue("SortControl")
    SORT_CONTROL("SortControl"),
    @XmlEnumValue("Table")
    TABLE("Table"),
    @XmlEnumValue("TableCell")
    TABLE_CELL("TableCell"),
    @XmlEnumValue("TableColumnStructure")
    TABLE_COLUMN_STRUCTURE("TableColumnStructure"),
    @XmlEnumValue("TableStructure")
    TABLE_STRUCTURE("TableStructure"),
    @XmlEnumValue("Transmission")
    TRANSMISSION("Transmission");
    private final String value;

    Classes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Classes fromValue(String v) {
        for (Classes c: Classes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
