//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.09 at 10:59:16 AM EST 
//


package org.cvrgrid.hl7aecg.jaxb.beans;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cs_AddressPartType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="cs_AddressPartType">
 *   &lt;restriction base="{urn:hl7-org:v3}cs">
 *     &lt;enumeration value="DEL"/>
 *     &lt;enumeration value="CNT"/>
 *     &lt;enumeration value="STA"/>
 *     &lt;enumeration value="CPA"/>
 *     &lt;enumeration value="CTY"/>
 *     &lt;enumeration value="ZIP"/>
 *     &lt;enumeration value="STR"/>
 *     &lt;enumeration value="HNR"/>
 *     &lt;enumeration value="SAL"/>
 *     &lt;enumeration value="DIR"/>
 *     &lt;enumeration value="ADL"/>
 *     &lt;enumeration value="POB"/>
 *     &lt;enumeration value="CEN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "cs_AddressPartType")
@XmlEnum
public enum CsAddressPartType {

    DEL,
    CNT,
    STA,
    CPA,
    CTY,
    ZIP,
    STR,
    HNR,
    SAL,
    DIR,
    ADL,
    POB,
    CEN;

    public String value() {
        return name();
    }

    public static CsAddressPartType fromValue(String v) {
        return valueOf(v);
    }

}
