//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.09 at 10:59:16 AM EST 
//


package org.cvrgrid.hl7aecg.jaxb.beans;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cs_Currency.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="cs_Currency">
 *   &lt;restriction base="{urn:hl7-org:v3}cs">
 *     &lt;enumeration value="ARS"/>
 *     &lt;enumeration value="AUD"/>
 *     &lt;enumeration value="ATS"/>
 *     &lt;enumeration value="BEF"/>
 *     &lt;enumeration value="BRL"/>
 *     &lt;enumeration value="CAD"/>
 *     &lt;enumeration value="CLF"/>
 *     &lt;enumeration value="CNY"/>
 *     &lt;enumeration value="CUP"/>
 *     &lt;enumeration value="EUR"/>
 *     &lt;enumeration value="XEU"/>
 *     &lt;enumeration value="FIM"/>
 *     &lt;enumeration value="FRF"/>
 *     &lt;enumeration value="DEM"/>
 *     &lt;enumeration value="INR"/>
 *     &lt;enumeration value="ILS"/>
 *     &lt;enumeration value="JPY"/>
 *     &lt;enumeration value="KRW"/>
 *     &lt;enumeration value="LUF"/>
 *     &lt;enumeration value="MXN"/>
 *     &lt;enumeration value="NLG"/>
 *     &lt;enumeration value="NZD"/>
 *     &lt;enumeration value="NOK"/>
 *     &lt;enumeration value="PHP"/>
 *     &lt;enumeration value="RUR"/>
 *     &lt;enumeration value="SGD"/>
 *     &lt;enumeration value="ZAR"/>
 *     &lt;enumeration value="ESP"/>
 *     &lt;enumeration value="SEK"/>
 *     &lt;enumeration value="CHF"/>
 *     &lt;enumeration value="THB"/>
 *     &lt;enumeration value="TWD"/>
 *     &lt;enumeration value="TRL"/>
 *     &lt;enumeration value="GBP"/>
 *     &lt;enumeration value="USD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "cs_Currency")
@XmlEnum
public enum CsCurrency {

    ARS,
    AUD,
    ATS,
    BEF,
    BRL,
    CAD,
    CLF,
    CNY,
    CUP,
    EUR,
    XEU,
    FIM,
    FRF,
    DEM,
    INR,
    ILS,
    JPY,
    KRW,
    LUF,
    MXN,
    NLG,
    NZD,
    NOK,
    PHP,
    RUR,
    SGD,
    ZAR,
    ESP,
    SEK,
    CHF,
    THB,
    TWD,
    TRL,
    GBP,
    USD;

    public String value() {
        return name();
    }

    public static CsCurrency fromValue(String v) {
        return valueOf(v);
    }

}
