//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.09 at 10:59:16 AM EST 
//


package org.cvrgrid.hl7aecg.jaxb.beans;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cs_EntityNamePartQualifier.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="cs_EntityNamePartQualifier">
 *   &lt;restriction base="{urn:hl7-org:v3}cs">
 *     &lt;enumeration value="BR"/>
 *     &lt;enumeration value="SP"/>
 *     &lt;enumeration value="VV"/>
 *     &lt;enumeration value="AC"/>
 *     &lt;enumeration value="PR"/>
 *     &lt;enumeration value="NB"/>
 *     &lt;enumeration value="LS"/>
 *     &lt;enumeration value="CL"/>
 *     &lt;enumeration value="IN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "cs_EntityNamePartQualifier")
@XmlEnum
public enum CsEntityNamePartQualifier {

    BR,
    SP,
    VV,
    AC,
    PR,
    NB,
    LS,
    CL,
    IN;

    public String value() {
        return name();
    }

    public static CsEntityNamePartQualifier fromValue(String v) {
        return valueOf(v);
    }

}
