//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.09 at 10:59:16 AM EST 
//


package org.cvrgrid.hl7aecg.jaxb.beans;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cs_ProbabilityDistributionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="cs_ProbabilityDistributionType">
 *   &lt;restriction base="{urn:hl7-org:v3}cs">
 *     &lt;enumeration value="U"/>
 *     &lt;enumeration value="N"/>
 *     &lt;enumeration value="LN"/>
 *     &lt;enumeration value="G"/>
 *     &lt;enumeration value="E"/>
 *     &lt;enumeration value="X2"/>
 *     &lt;enumeration value="T"/>
 *     &lt;enumeration value="F"/>
 *     &lt;enumeration value="B"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "cs_ProbabilityDistributionType")
@XmlEnum
public enum CsProbabilityDistributionType {

    U("U"),
    N("N"),
    LN("LN"),
    G("G"),
    E("E"),
    @XmlEnumValue("X2")
    X_2("X2"),
    T("T"),
    F("F"),
    B("B");
    private final String value;

    CsProbabilityDistributionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CsProbabilityDistributionType fromValue(String v) {
        for (CsProbabilityDistributionType c: CsProbabilityDistributionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
