//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.09 at 10:59:16 AM EST 
//


package org.cvrgrid.hl7aecg.jaxb.beans;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DocumentTableRowStructure.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DocumentTableRowStructure">
 *   &lt;restriction base="{urn:hl7-org:v3}DocumentTableStructure">
 *     &lt;enumeration value="tbody"/>
 *     &lt;enumeration value="tfoot"/>
 *     &lt;enumeration value="thead"/>
 *     &lt;enumeration value="TBLROW"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DocumentTableRowStructure")
@XmlEnum(DocumentTableStructure.class)
public enum DocumentTableRowStructure {

    @XmlEnumValue("tbody")
    TBODY(DocumentTableStructure.TBODY),
    @XmlEnumValue("tfoot")
    TFOOT(DocumentTableStructure.TFOOT),
    @XmlEnumValue("thead")
    THEAD(DocumentTableStructure.THEAD),
    TBLROW(DocumentTableStructure.TBLROW);
    private final DocumentTableStructure value;

    DocumentTableRowStructure(DocumentTableStructure v) {
        value = v;
    }

    public DocumentTableStructure value() {
        return value;
    }

    public static DocumentTableRowStructure fromValue(DocumentTableStructure v) {
        for (DocumentTableRowStructure c: DocumentTableRowStructure.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
