//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.09 at 10:59:16 AM EST 
//


package org.cvrgrid.hl7aecg.jaxb.beans;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DocumentTableRowGroup.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DocumentTableRowGroup">
 *   &lt;restriction base="{urn:hl7-org:v3}DocumentTableRowStructure">
 *     &lt;enumeration value="tbody"/>
 *     &lt;enumeration value="tfoot"/>
 *     &lt;enumeration value="thead"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DocumentTableRowGroup")
@XmlEnum(DocumentTableRowStructure.class)
public enum DocumentTableRowGroup {

    @XmlEnumValue("tbody")
    TBODY(DocumentTableRowStructure.TBODY),
    @XmlEnumValue("tfoot")
    TFOOT(DocumentTableRowStructure.TFOOT),
    @XmlEnumValue("thead")
    THEAD(DocumentTableRowStructure.THEAD);
    private final DocumentTableRowStructure value;

    DocumentTableRowGroup(DocumentTableRowStructure v) {
        value = v;
    }

    public DocumentTableRowStructure value() {
        return value;
    }

    public static DocumentTableRowGroup fromValue(DocumentTableRowStructure v) {
        for (DocumentTableRowGroup c: DocumentTableRowGroup.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
