//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.09 at 10:59:16 AM EST 
//


package org.cvrgrid.hl7aecg.jaxb.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				2003-10-02: pvb: see xs:annotation/xs:documentation for ED, EC and SC...
 * 				this type is the equivalent of EC but for ADXP rather than SC
 * 			
 * 
 * <p>Java class for EAXP complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EAXP">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:v3}ED">
 *       &lt;attribute name="partType" type="{urn:hl7-org:v3}cs_AddressPartType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EAXP")
@XmlSeeAlso({
    ADXP.class
})
public abstract class EAXP
    extends ED
{

    @XmlAttribute(name = "partType")
    protected CsAddressPartType partType;

    /**
     * Gets the value of the partType property.
     * 
     * @return
     *     possible object is
     *     {@link CsAddressPartType }
     *     
     */
    public CsAddressPartType getPartType() {
        return partType;
    }

    /**
     * Sets the value of the partType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CsAddressPartType }
     *     
     */
    public void setPartType(CsAddressPartType value) {
        this.partType = value;
    }

}
