//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.09 at 10:59:16 AM EST 
//


package org.cvrgrid.hl7aecg.jaxb.beans;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.cvrgrid.hl7aecg package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Foo_QNAME = new QName("urn:hl7-org:v3", "foo");
    private final static QName _AnnotatedECG_QNAME = new QName("urn:hl7-org:v3", "AnnotatedECG");
    private final static QName _LeafTerm_QNAME = new QName("urn:hl7-org:v3:meta:voc", "leafTerm");
    private final static QName _SpecDomain_QNAME = new QName("urn:hl7-org:v3:meta:voc", "specDomain");
    private final static QName _ADStreetName_QNAME = new QName("urn:hl7-org:v3", "streetName");
    private final static QName _ADHouseNumber_QNAME = new QName("urn:hl7-org:v3", "houseNumber");
    private final static QName _ADState_QNAME = new QName("urn:hl7-org:v3", "state");
    private final static QName _ADPostBox_QNAME = new QName("urn:hl7-org:v3", "postBox");
    private final static QName _ADCity_QNAME = new QName("urn:hl7-org:v3", "city");
    private final static QName _ADCountry_QNAME = new QName("urn:hl7-org:v3", "country");
    private final static QName _ADAdditionalLocator_QNAME = new QName("urn:hl7-org:v3", "additionalLocator");
    private final static QName _ADStreetAddressLine_QNAME = new QName("urn:hl7-org:v3", "streetAddressLine");
    private final static QName _ADDirection_QNAME = new QName("urn:hl7-org:v3", "direction");
    private final static QName _ADCensusTract_QNAME = new QName("urn:hl7-org:v3", "censusTract");
    private final static QName _ADPostalCode_QNAME = new QName("urn:hl7-org:v3", "postalCode");
    private final static QName _ADDelimiter_QNAME = new QName("urn:hl7-org:v3", "delimiter");
    private final static QName _ADValidTime_QNAME = new QName("urn:hl7-org:v3", "validTime");
    private final static QName _ADCounty_QNAME = new QName("urn:hl7-org:v3", "county");
    private final static QName _IVLINTHigh_QNAME = new QName("urn:hl7-org:v3", "high");
    private final static QName _IVLINTLow_QNAME = new QName("urn:hl7-org:v3", "low");
    private final static QName _IVLINTCenter_QNAME = new QName("urn:hl7-org:v3", "center");
    private final static QName _IVLINTWidth_QNAME = new QName("urn:hl7-org:v3", "width");
    private final static QName _HXITPQTranslation_QNAME = new QName("urn:hl7-org:v3", "translation");
    private final static QName _ENSuffix_QNAME = new QName("urn:hl7-org:v3", "suffix");
    private final static QName _ENPrefix_QNAME = new QName("urn:hl7-org:v3", "prefix");
    private final static QName _ENFamily_QNAME = new QName("urn:hl7-org:v3", "family");
    private final static QName _ENGiven_QNAME = new QName("urn:hl7-org:v3", "given");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.cvrgrid.hl7aecg
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PORTMT020001Component7 }
     * 
     */
    public PORTMT020001Component7 createPORTMT020001Component7() {
        return new PORTMT020001Component7();
    }

    /**
     * Create an instance of {@link IVLTS }
     * 
     */
    public IVLTS createIVLTS() {
        return new IVLTS();
    }

    /**
     * Create an instance of {@link SXCMPPDTS }
     * 
     */
    public SXCMPPDTS createSXCMPPDTS() {
        return new SXCMPPDTS();
    }

    /**
     * Create an instance of {@link org.cvrgrid.hl7aecg.jaxb.beans.RTOQTYQTY.Numerator }
     * 
     */
    public org.cvrgrid.hl7aecg.jaxb.beans.RTOQTYQTY.Numerator createRTOQTYQTYNumerator() {
        return new org.cvrgrid.hl7aecg.jaxb.beans.RTOQTYQTY.Numerator();
    }

    /**
     * Create an instance of {@link PORTMT020001AssignedEntity }
     * 
     */
    public PORTMT020001AssignedEntity createPORTMT020001AssignedEntity() {
        return new PORTMT020001AssignedEntity();
    }

    /**
     * Create an instance of {@link ADXP }
     * 
     */
    public ADXP createADXP() {
        return new ADXP();
    }

    /**
     * Create an instance of {@link ENXP }
     * 
     */
    public ENXP createENXP() {
        return new ENXP();
    }

    /**
     * Create an instance of {@link PORTMT020001Author }
     * 
     */
    public PORTMT020001Author createPORTMT020001Author() {
        return new PORTMT020001Author();
    }

    /**
     * Create an instance of {@link SLISTPQ }
     * 
     */
    public SLISTPQ createSLISTPQ() {
        return new SLISTPQ();
    }

    /**
     * Create an instance of {@link PORTMT020001Component }
     * 
     */
    public PORTMT020001Component createPORTMT020001Component() {
        return new PORTMT020001Component();
    }

    /**
     * Create an instance of {@link PORTMT020001Subject1 }
     * 
     */
    public PORTMT020001Subject1 createPORTMT020001Subject1() {
        return new PORTMT020001Subject1();
    }

    /**
     * Create an instance of {@link PORTMT020001Component4 }
     * 
     */
    public PORTMT020001Component4 createPORTMT020001Component4() {
        return new PORTMT020001Component4();
    }

    /**
     * Create an instance of {@link AD.StreetName }
     * 
     */
    public AD.StreetName createADStreetName() {
        return new AD.StreetName();
    }

    /**
     * Create an instance of {@link PORTMT020001Performer2 }
     * 
     */
    public PORTMT020001Performer2 createPORTMT020001Performer2() {
        return new PORTMT020001Performer2();
    }

    /**
     * Create an instance of {@link SXCMMO }
     * 
     */
    public SXCMMO createSXCMMO() {
        return new SXCMMO();
    }

    /**
     * Create an instance of {@link AD.City }
     * 
     */
    public AD.City createADCity() {
        return new AD.City();
    }

    /**
     * Create an instance of {@link RTOMOPQ }
     * 
     */
    public RTOMOPQ createRTOMOPQ() {
        return new RTOMOPQ();
    }

    /**
     * Create an instance of {@link PORTMT020001Location1 }
     * 
     */
    public PORTMT020001Location1 createPORTMT020001Location1() {
        return new PORTMT020001Location1();
    }

    /**
     * Create an instance of {@link IVLINT }
     * 
     */
    public IVLINT createIVLINT() {
        return new IVLINT();
    }

    /**
     * Create an instance of {@link RTOPQPQ.Denominator }
     * 
     */
    public RTOPQPQ.Denominator createRTOPQPQDenominator() {
        return new RTOPQPQ.Denominator();
    }

    /**
     * Create an instance of {@link PORTMT020001TrialSubject }
     * 
     */
    public PORTMT020001TrialSubject createPORTMT020001TrialSubject() {
        return new PORTMT020001TrialSubject();
    }

    /**
     * Create an instance of {@link HXITPQ }
     * 
     */
    public HXITPQ createHXITPQ() {
        return new HXITPQ();
    }

    /**
     * Create an instance of {@link PORTMT020001Annotation }
     * 
     */
    public PORTMT020001Annotation createPORTMT020001Annotation() {
        return new PORTMT020001Annotation();
    }

    /**
     * Create an instance of {@link PORTMT020001ManufacturedDevice }
     * 
     */
    public PORTMT020001ManufacturedDevice createPORTMT020001ManufacturedDevice() {
        return new PORTMT020001ManufacturedDevice();
    }

    /**
     * Create an instance of {@link PORTMT020001ControlVariable6 }
     * 
     */
    public PORTMT020001ControlVariable6 createPORTMT020001ControlVariable6() {
        return new PORTMT020001ControlVariable6();
    }

    /**
     * Create an instance of {@link ED }
     * 
     */
    public ED createED() {
        return new ED();
    }

    /**
     * Create an instance of {@link PORTMT020001ROI }
     * 
     */
    public PORTMT020001ROI createPORTMT020001ROI() {
        return new PORTMT020001ROI();
    }

    /**
     * Create an instance of {@link VocabItem }
     * 
     */
    public VocabItem createVocabItem() {
        return new VocabItem();
    }

    /**
     * Create an instance of {@link PORTMT020001ProtocolTimepointEvent }
     * 
     */
    public PORTMT020001ProtocolTimepointEvent createPORTMT020001ProtocolTimepointEvent() {
        return new PORTMT020001ProtocolTimepointEvent();
    }

    /**
     * Create an instance of {@link PORTMT020001AuthoringOrganization }
     * 
     */
    public PORTMT020001AuthoringOrganization createPORTMT020001AuthoringOrganization() {
        return new PORTMT020001AuthoringOrganization();
    }

    /**
     * Create an instance of {@link SXCMINT }
     * 
     */
    public SXCMINT createSXCMINT() {
        return new SXCMINT();
    }

    /**
     * Create an instance of {@link CR }
     * 
     */
    public CR createCR() {
        return new CR();
    }

    /**
     * Create an instance of {@link PORTMT020001RelatedObservation }
     * 
     */
    public PORTMT020001RelatedObservation createPORTMT020001RelatedObservation() {
        return new PORTMT020001RelatedObservation();
    }

    /**
     * Create an instance of {@link IVLPPDTS }
     * 
     */
    public IVLPPDTS createIVLPPDTS() {
        return new IVLPPDTS();
    }

    /**
     * Create an instance of {@link PORTMT020001StudyEventPerformer }
     * 
     */
    public PORTMT020001StudyEventPerformer createPORTMT020001StudyEventPerformer() {
        return new PORTMT020001StudyEventPerformer();
    }

    /**
     * Create an instance of {@link PORTMT020001ControlVariable5 }
     * 
     */
    public PORTMT020001ControlVariable5 createPORTMT020001ControlVariable5() {
        return new PORTMT020001ControlVariable5();
    }

    /**
     * Create an instance of {@link PORTMT020001SeriesPerformer }
     * 
     */
    public PORTMT020001SeriesPerformer createPORTMT020001SeriesPerformer() {
        return new PORTMT020001SeriesPerformer();
    }

    /**
     * Create an instance of {@link PORTMT020001ClinicalTrialProtocol }
     * 
     */
    public PORTMT020001ClinicalTrialProtocol createPORTMT020001ClinicalTrialProtocol() {
        return new PORTMT020001ClinicalTrialProtocol();
    }

    /**
     * Create an instance of {@link PORTMT020001ClinicalTrial }
     * 
     */
    public PORTMT020001ClinicalTrial createPORTMT020001ClinicalTrial() {
        return new PORTMT020001ClinicalTrial();
    }

    /**
     * Create an instance of {@link PORTMT020001SeriesAuthor }
     * 
     */
    public PORTMT020001SeriesAuthor createPORTMT020001SeriesAuthor() {
        return new PORTMT020001SeriesAuthor();
    }

    /**
     * Create an instance of {@link RTOPQPQ.Numerator }
     * 
     */
    public RTOPQPQ.Numerator createRTOPQPQNumerator() {
        return new RTOPQPQ.Numerator();
    }

    /**
     * Create an instance of {@link PORTMT020001ReferenceEvent }
     * 
     */
    public PORTMT020001ReferenceEvent createPORTMT020001ReferenceEvent() {
        return new PORTMT020001ReferenceEvent();
    }

    /**
     * Create an instance of {@link REAL }
     * 
     */
    public REAL createREAL() {
        return new REAL();
    }

    /**
     * Create an instance of {@link PPDPQ }
     * 
     */
    public PPDPQ createPPDPQ() {
        return new PPDPQ();
    }

    /**
     * Create an instance of {@link PN }
     * 
     */
    public PN createPN() {
        return new PN();
    }

    /**
     * Create an instance of {@link PORTMT020001Component12 }
     * 
     */
    public PORTMT020001Component12 createPORTMT020001Component12() {
        return new PORTMT020001Component12();
    }

    /**
     * Create an instance of {@link PORTMT020001ResponsibleParty }
     * 
     */
    public PORTMT020001ResponsibleParty createPORTMT020001ResponsibleParty() {
        return new PORTMT020001ResponsibleParty();
    }

    /**
     * Create an instance of {@link PORTMT020001Subject2 }
     * 
     */
    public PORTMT020001Subject2 createPORTMT020001Subject2() {
        return new PORTMT020001Subject2();
    }

    /**
     * Create an instance of {@link SXCMTS }
     * 
     */
    public SXCMTS createSXCMTS() {
        return new SXCMTS();
    }

    /**
     * Create an instance of {@link PORTMT020001DerivedFrom }
     * 
     */
    public PORTMT020001DerivedFrom createPORTMT020001DerivedFrom() {
        return new PORTMT020001DerivedFrom();
    }

    /**
     * Create an instance of {@link IVLMO }
     * 
     */
    public IVLMO createIVLMO() {
        return new IVLMO();
    }

    /**
     * Create an instance of {@link CS }
     * 
     */
    public CS createCS() {
        return new CS();
    }

    /**
     * Create an instance of {@link PORTMT020001AuthorTypeComp21 }
     * 
     */
    public PORTMT020001AuthorTypeComp21 createPORTMT020001AuthorTypeComp21() {
        return new PORTMT020001AuthorTypeComp21();
    }

    /**
     * Create an instance of {@link TSInc }
     * 
     */
    public TSInc createTSInc() {
        return new TSInc();
    }

    /**
     * Create an instance of {@link MO }
     * 
     */
    public MO createMO() {
        return new MO();
    }

    /**
     * Create an instance of {@link RTOMOPQ.Denominator }
     * 
     */
    public RTOMOPQ.Denominator createRTOMOPQDenominator() {
        return new RTOMOPQ.Denominator();
    }

    /**
     * Create an instance of {@link AD.StreetAddressLine }
     * 
     */
    public AD.StreetAddressLine createADStreetAddressLine() {
        return new AD.StreetAddressLine();
    }

    /**
     * Create an instance of {@link GLISTPQ }
     * 
     */
    public GLISTPQ createGLISTPQ() {
        return new GLISTPQ();
    }

    /**
     * Create an instance of {@link PORTMT020001SeriesDevice }
     * 
     */
    public PORTMT020001SeriesDevice createPORTMT020001SeriesDevice() {
        return new PORTMT020001SeriesDevice();
    }

    /**
     * Create an instance of {@link PORTMT020001Author1 }
     * 
     */
    public PORTMT020001Author1 createPORTMT020001Author1() {
        return new PORTMT020001Author1();
    }

    /**
     * Create an instance of {@link PORTMT020001SecondaryPerformer }
     * 
     */
    public PORTMT020001SecondaryPerformer createPORTMT020001SecondaryPerformer() {
        return new PORTMT020001SecondaryPerformer();
    }

    /**
     * Create an instance of {@link PORTMT020001Component6 }
     * 
     */
    public PORTMT020001Component6 createPORTMT020001Component6() {
        return new PORTMT020001Component6();
    }

    /**
     * Create an instance of {@link PORTMT020001AuthorTypeComp22 }
     * 
     */
    public PORTMT020001AuthorTypeComp22 createPORTMT020001AuthorTypeComp22() {
        return new PORTMT020001AuthorTypeComp22();
    }

    /**
     * Create an instance of {@link URL }
     * 
     */
    public URL createURL() {
        return new URL();
    }

    /**
     * Create an instance of {@link PORTMT020001Component3 }
     * 
     */
    public PORTMT020001Component3 createPORTMT020001Component3() {
        return new PORTMT020001Component3();
    }

    /**
     * Create an instance of {@link PORTMT020001ClinicalTrialSponsor }
     * 
     */
    public PORTMT020001ClinicalTrialSponsor createPORTMT020001ClinicalTrialSponsor() {
        return new PORTMT020001ClinicalTrialSponsor();
    }

    /**
     * Create an instance of {@link PORTMT020001TrialInvestigator }
     * 
     */
    public PORTMT020001TrialInvestigator createPORTMT020001TrialInvestigator() {
        return new PORTMT020001TrialInvestigator();
    }

    /**
     * Create an instance of {@link EnDel }
     * 
     */
    public EnDel createEnDel() {
        return new EnDel();
    }

    /**
     * Create an instance of {@link AD }
     * 
     */
    public AD createAD() {
        return new AD();
    }

    /**
     * Create an instance of {@link PORTMT020001Boundary }
     * 
     */
    public PORTMT020001Boundary createPORTMT020001Boundary() {
        return new PORTMT020001Boundary();
    }

    /**
     * Create an instance of {@link PORTMT020001Author4 }
     * 
     */
    public PORTMT020001Author4 createPORTMT020001Author4() {
        return new PORTMT020001Author4();
    }

    /**
     * Create an instance of {@link PORTMT020001Series }
     * 
     */
    public PORTMT020001Series createPORTMT020001Series() {
        return new PORTMT020001Series();
    }

    /**
     * Create an instance of {@link PORTMT020001Support1 }
     * 
     */
    public PORTMT020001Support1 createPORTMT020001Support1() {
        return new PORTMT020001Support1();
    }

    /**
     * Create an instance of {@link PORTMT020001Author2 }
     * 
     */
    public PORTMT020001Author2 createPORTMT020001Author2() {
        return new PORTMT020001Author2();
    }

    /**
     * Create an instance of {@link PORTMT020001TestingSite }
     * 
     */
    public PORTMT020001TestingSite createPORTMT020001TestingSite() {
        return new PORTMT020001TestingSite();
    }

    /**
     * Create an instance of {@link BIN }
     * 
     */
    public BIN createBIN() {
        return new BIN();
    }

    /**
     * Create an instance of {@link CD }
     * 
     */
    public CD createCD() {
        return new CD();
    }

    /**
     * Create an instance of {@link PORTMT020001Sequence }
     * 
     */
    public PORTMT020001Sequence createPORTMT020001Sequence() {
        return new PORTMT020001Sequence();
    }

    /**
     * Create an instance of {@link PPDTS }
     * 
     */
    public PPDTS createPPDTS() {
        return new PPDTS();
    }

    /**
     * Create an instance of {@link PORTMT020001Support2 }
     * 
     */
    public PORTMT020001Support2 createPORTMT020001Support2() {
        return new PORTMT020001Support2();
    }

    /**
     * Create an instance of {@link AD.Direction }
     * 
     */
    public AD.Direction createADDirection() {
        return new AD.Direction();
    }

    /**
     * Create an instance of {@link PQ }
     * 
     */
    public PQ createPQ() {
        return new PQ();
    }

    /**
     * Create an instance of {@link PORTMT020001Device }
     * 
     */
    public PORTMT020001Device createPORTMT020001Device() {
        return new PORTMT020001Device();
    }

    /**
     * Create an instance of {@link PORTMT020001TrialSite }
     * 
     */
    public PORTMT020001TrialSite createPORTMT020001TrialSite() {
        return new PORTMT020001TrialSite();
    }

    /**
     * Create an instance of {@link PORTMT020001Definition3 }
     * 
     */
    public PORTMT020001Definition3 createPORTMT020001Definition3() {
        return new PORTMT020001Definition3();
    }

    /**
     * Create an instance of {@link PORTMT020001FindingComment }
     * 
     */
    public PORTMT020001FindingComment createPORTMT020001FindingComment() {
        return new PORTMT020001FindingComment();
    }

    /**
     * Create an instance of {@link II }
     * 
     */
    public II createII() {
        return new II();
    }

    /**
     * Create an instance of {@link org.cvrgrid.hl7aecg.jaxb.beans.RTOQTYQTY.Denominator }
     * 
     */
    public org.cvrgrid.hl7aecg.jaxb.beans.RTOQTYQTY.Denominator createRTOQTYQTYDenominator() {
        return new org.cvrgrid.hl7aecg.jaxb.beans.RTOQTYQTY.Denominator();
    }

    /**
     * Create an instance of {@link PORTMT020001ControlVariable4 }
     * 
     */
    public PORTMT020001ControlVariable4 createPORTMT020001ControlVariable4() {
        return new PORTMT020001ControlVariable4();
    }

    /**
     * Create an instance of {@link SC }
     * 
     */
    public SC createSC() {
        return new SC();
    }

    /**
     * Create an instance of {@link RTOMOPQ.Numerator }
     * 
     */
    public RTOMOPQ.Numerator createRTOMOPQNumerator() {
        return new RTOMOPQ.Numerator();
    }

    /**
     * Create an instance of {@link MOInc }
     * 
     */
    public MOInc createMOInc() {
        return new MOInc();
    }

    /**
     * Create an instance of {@link AD.PostBox }
     * 
     */
    public AD.PostBox createADPostBox() {
        return new AD.PostBox();
    }

    /**
     * Create an instance of {@link IVLPQ }
     * 
     */
    public IVLPQ createIVLPQ() {
        return new IVLPQ();
    }

    /**
     * Create an instance of {@link SXCMCD }
     * 
     */
    public SXCMCD createSXCMCD() {
        return new SXCMCD();
    }

    /**
     * Create an instance of {@link PORTMT020001TimepointEvent }
     * 
     */
    public PORTMT020001TimepointEvent createPORTMT020001TimepointEvent() {
        return new PORTMT020001TimepointEvent();
    }

    /**
     * Create an instance of {@link PORTMT020001IdentifiedEntity }
     * 
     */
    public PORTMT020001IdentifiedEntity createPORTMT020001IdentifiedEntity() {
        return new PORTMT020001IdentifiedEntity();
    }

    /**
     * Create an instance of {@link AD.Delimiter }
     * 
     */
    public AD.Delimiter createADDelimiter() {
        return new AD.Delimiter();
    }

    /**
     * Create an instance of {@link EN }
     * 
     */
    public EN createEN() {
        return new EN();
    }

    /**
     * Create an instance of {@link GLISTTS }
     * 
     */
    public GLISTTS createGLISTTS() {
        return new GLISTTS();
    }

    /**
     * Create an instance of {@link PORTMT020001Component9 }
     * 
     */
    public PORTMT020001Component9 createPORTMT020001Component9() {
        return new PORTMT020001Component9();
    }

    /**
     * Create an instance of {@link TN }
     * 
     */
    public TN createTN() {
        return new TN();
    }

    /**
     * Create an instance of {@link PORTMT020001Component10 }
     * 
     */
    public PORTMT020001Component10 createPORTMT020001Component10() {
        return new PORTMT020001Component10();
    }

    /**
     * Create an instance of {@link PORTMT020001TreatmentGroupAssignment }
     * 
     */
    public PORTMT020001TreatmentGroupAssignment createPORTMT020001TreatmentGroupAssignment() {
        return new PORTMT020001TreatmentGroupAssignment();
    }

    /**
     * Create an instance of {@link AD.County }
     * 
     */
    public AD.County createADCounty() {
        return new AD.County();
    }

    /**
     * Create an instance of {@link ON }
     * 
     */
    public ON createON() {
        return new ON();
    }

    /**
     * Create an instance of {@link PORTMT020001AuthorTypeComp11 }
     * 
     */
    public PORTMT020001AuthorTypeComp11 createPORTMT020001AuthorTypeComp11() {
        return new PORTMT020001AuthorTypeComp11();
    }

    /**
     * Create an instance of {@link CE }
     * 
     */
    public CE createCE() {
        return new CE();
    }

    /**
     * Create an instance of {@link PORTMT020001Definition1 }
     * 
     */
    public PORTMT020001Definition1 createPORTMT020001Definition1() {
        return new PORTMT020001Definition1();
    }

    /**
     * Create an instance of {@link AD.CensusTract }
     * 
     */
    public AD.CensusTract createADCensusTract() {
        return new AD.CensusTract();
    }

    /**
     * Create an instance of {@link PORTMT020001Location }
     * 
     */
    public PORTMT020001Location createPORTMT020001Location() {
        return new PORTMT020001Location();
    }

    /**
     * Create an instance of {@link PORTMT020001AnnotationSet }
     * 
     */
    public PORTMT020001AnnotationSet createPORTMT020001AnnotationSet() {
        return new PORTMT020001AnnotationSet();
    }

    /**
     * Create an instance of {@link AD.Country }
     * 
     */
    public AD.Country createADCountry() {
        return new AD.Country();
    }

    /**
     * Create an instance of {@link PORTMT020001Component1 }
     * 
     */
    public PORTMT020001Component1 createPORTMT020001Component1() {
        return new PORTMT020001Component1();
    }

    /**
     * Create an instance of {@link ST }
     * 
     */
    public ST createST() {
        return new ST();
    }

    /**
     * Create an instance of {@link AD.HouseNumber }
     * 
     */
    public AD.HouseNumber createADHouseNumber() {
        return new AD.HouseNumber();
    }

    /**
     * Create an instance of {@link PORTMT020001Component8 }
     * 
     */
    public PORTMT020001Component8 createPORTMT020001Component8() {
        return new PORTMT020001Component8();
    }

    /**
     * Create an instance of {@link PIVLTS }
     * 
     */
    public PIVLTS createPIVLTS() {
        return new PIVLTS();
    }

    /**
     * Create an instance of {@link PORTMT020001Component11 }
     * 
     */
    public PORTMT020001Component11 createPORTMT020001Component11() {
        return new PORTMT020001Component11();
    }

    /**
     * Create an instance of {@link TS }
     * 
     */
    public TS createTS() {
        return new TS();
    }

    /**
     * Create an instance of {@link EDNoTn }
     * 
     */
    public EDNoTn createEDNoTn() {
        return new EDNoTn();
    }

    /**
     * Create an instance of {@link PORTMT020001Organization }
     * 
     */
    public PORTMT020001Organization createPORTMT020001Organization() {
        return new PORTMT020001Organization();
    }

    /**
     * Create an instance of {@link PORTMT020001SubjectAssignment }
     * 
     */
    public PORTMT020001SubjectAssignment createPORTMT020001SubjectAssignment() {
        return new PORTMT020001SubjectAssignment();
    }

    /**
     * Create an instance of {@link PORTMT020001AuthorType }
     * 
     */
    public PORTMT020001AuthorType createPORTMT020001AuthorType() {
        return new PORTMT020001AuthorType();
    }

    /**
     * Create an instance of {@link SXCMPQ }
     * 
     */
    public SXCMPQ createSXCMPQ() {
        return new SXCMPQ();
    }

    /**
     * Create an instance of {@link EnPfx }
     * 
     */
    public EnPfx createEnPfx() {
        return new EnPfx();
    }

    /**
     * Create an instance of {@link AD.PostalCode }
     * 
     */
    public AD.PostalCode createADPostalCode() {
        return new AD.PostalCode();
    }

    /**
     * Create an instance of {@link PORTMT020001DemographicPerson }
     * 
     */
    public PORTMT020001DemographicPerson createPORTMT020001DemographicPerson() {
        return new PORTMT020001DemographicPerson();
    }

    /**
     * Create an instance of {@link CV }
     * 
     */
    public CV createCV() {
        return new CV();
    }

    /**
     * Create an instance of {@link RTOPQPQ }
     * 
     */
    public RTOPQPQ createRTOPQPQ() {
        return new RTOPQPQ();
    }

    /**
     * Create an instance of {@link OID }
     * 
     */
    public OID createOID() {
        return new OID();
    }

    /**
     * Create an instance of {@link EnSfx }
     * 
     */
    public EnSfx createEnSfx() {
        return new EnSfx();
    }

    /**
     * Create an instance of {@link PQR }
     * 
     */
    public PQR createPQR() {
        return new PQR();
    }

    /**
     * Create an instance of {@link BXITCD }
     * 
     */
    public BXITCD createBXITCD() {
        return new BXITCD();
    }

    /**
     * Create an instance of {@link EnFam }
     * 
     */
    public EnFam createEnFam() {
        return new EnFam();
    }

    /**
     * Create an instance of {@link PORTMT020001PertinentInformation }
     * 
     */
    public PORTMT020001PertinentInformation createPORTMT020001PertinentInformation() {
        return new PORTMT020001PertinentInformation();
    }

    /**
     * Create an instance of {@link PORTMT020001ControlVariable }
     * 
     */
    public PORTMT020001ControlVariable createPORTMT020001ControlVariable() {
        return new PORTMT020001ControlVariable();
    }

    /**
     * Create an instance of {@link AD.AdditionalLocator }
     * 
     */
    public AD.AdditionalLocator createADAdditionalLocator() {
        return new AD.AdditionalLocator();
    }

    /**
     * Create an instance of {@link TEL }
     * 
     */
    public TEL createTEL() {
        return new TEL();
    }

    /**
     * Create an instance of {@link PORTMT020001AnnotatedECG }
     * 
     */
    public PORTMT020001AnnotatedECG createPORTMT020001AnnotatedECG() {
        return new PORTMT020001AnnotatedECG();
    }

    /**
     * Create an instance of {@link PORTMT020001ControlVariable1 }
     * 
     */
    public PORTMT020001ControlVariable1 createPORTMT020001ControlVariable1() {
        return new PORTMT020001ControlVariable1();
    }

    /**
     * Create an instance of {@link INTInc }
     * 
     */
    public INTInc createINTInc() {
        return new INTInc();
    }

    /**
     * Create an instance of {@link PORTMT020001RelativeTimepoint }
     * 
     */
    public PORTMT020001RelativeTimepoint createPORTMT020001RelativeTimepoint() {
        return new PORTMT020001RelativeTimepoint();
    }

    /**
     * Create an instance of {@link BL }
     * 
     */
    public BL createBL() {
        return new BL();
    }

    /**
     * Create an instance of {@link PQInc }
     * 
     */
    public PQInc createPQInc() {
        return new PQInc();
    }

    /**
     * Create an instance of {@link PORTMT020001SequenceSet }
     * 
     */
    public PORTMT020001SequenceSet createPORTMT020001SequenceSet() {
        return new PORTMT020001SequenceSet();
    }

    /**
     * Create an instance of {@link PIVLPPDTS }
     * 
     */
    public PIVLPPDTS createPIVLPPDTS() {
        return new PIVLPPDTS();
    }

    /**
     * Create an instance of {@link PORTMT020001Author3 }
     * 
     */
    public PORTMT020001Author3 createPORTMT020001Author3() {
        return new PORTMT020001Author3();
    }

    /**
     * Create an instance of {@link PORTMT020001Component5 }
     * 
     */
    public PORTMT020001Component5 createPORTMT020001Component5() {
        return new PORTMT020001Component5();
    }

    /**
     * Create an instance of {@link PORTMT020001Component2 }
     * 
     */
    public PORTMT020001Component2 createPORTMT020001Component2() {
        return new PORTMT020001Component2();
    }

    /**
     * Create an instance of {@link PORTMT020001Person }
     * 
     */
    public PORTMT020001Person createPORTMT020001Person() {
        return new PORTMT020001Person();
    }

    /**
     * Create an instance of {@link PORTMT020001Location2 }
     * 
     */
    public PORTMT020001Location2 createPORTMT020001Location2() {
        return new PORTMT020001Location2();
    }

    /**
     * Create an instance of {@link AD.State }
     * 
     */
    public AD.State createADState() {
        return new AD.State();
    }

    /**
     * Create an instance of {@link EnGiv }
     * 
     */
    public EnGiv createEnGiv() {
        return new EnGiv();
    }

    /**
     * Create an instance of {@link INT }
     * 
     */
    public INT createINT() {
        return new INT();
    }

    /**
     * Create an instance of {@link IVLPPDTS.Low }
     * 
     */
    public IVLPPDTS.Low createIVLPPDTSLow() {
        return new IVLPPDTS.Low();
    }

    /**
     * Create an instance of {@link PORTMT020001ControlVariable3 }
     * 
     */
    public PORTMT020001ControlVariable3 createPORTMT020001ControlVariable3() {
        return new PORTMT020001ControlVariable3();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SC }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "foo")
    public JAXBElement<SC> createFoo(SC value) {
        return new JAXBElement<SC>(_Foo_QNAME, SC.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PORTMT020001AnnotatedECG }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "AnnotatedECG")
    public JAXBElement<PORTMT020001AnnotatedECG> createAnnotatedECG(PORTMT020001AnnotatedECG value) {
        return new JAXBElement<PORTMT020001AnnotatedECG>(_AnnotatedECG_QNAME, PORTMT020001AnnotatedECG.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VocabItem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3:meta:voc", name = "leafTerm")
    public JAXBElement<VocabItem> createLeafTerm(VocabItem value) {
        return new JAXBElement<VocabItem>(_LeafTerm_QNAME, VocabItem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VocabItem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3:meta:voc", name = "specDomain")
    public JAXBElement<VocabItem> createSpecDomain(VocabItem value) {
        return new JAXBElement<VocabItem>(_SpecDomain_QNAME, VocabItem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AD.StreetName }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "streetName", scope = AD.class)
    public JAXBElement<AD.StreetName> createADStreetName(AD.StreetName value) {
        return new JAXBElement<AD.StreetName>(_ADStreetName_QNAME, AD.StreetName.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AD.HouseNumber }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "houseNumber", scope = AD.class)
    public JAXBElement<AD.HouseNumber> createADHouseNumber(AD.HouseNumber value) {
        return new JAXBElement<AD.HouseNumber>(_ADHouseNumber_QNAME, AD.HouseNumber.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AD.State }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "state", scope = AD.class)
    public JAXBElement<AD.State> createADState(AD.State value) {
        return new JAXBElement<AD.State>(_ADState_QNAME, AD.State.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AD.PostBox }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "postBox", scope = AD.class)
    public JAXBElement<AD.PostBox> createADPostBox(AD.PostBox value) {
        return new JAXBElement<AD.PostBox>(_ADPostBox_QNAME, AD.PostBox.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AD.City }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "city", scope = AD.class)
    public JAXBElement<AD.City> createADCity(AD.City value) {
        return new JAXBElement<AD.City>(_ADCity_QNAME, AD.City.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AD.Country }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "country", scope = AD.class)
    public JAXBElement<AD.Country> createADCountry(AD.Country value) {
        return new JAXBElement<AD.Country>(_ADCountry_QNAME, AD.Country.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AD.AdditionalLocator }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "additionalLocator", scope = AD.class)
    public JAXBElement<AD.AdditionalLocator> createADAdditionalLocator(AD.AdditionalLocator value) {
        return new JAXBElement<AD.AdditionalLocator>(_ADAdditionalLocator_QNAME, AD.AdditionalLocator.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AD.StreetAddressLine }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "streetAddressLine", scope = AD.class)
    public JAXBElement<AD.StreetAddressLine> createADStreetAddressLine(AD.StreetAddressLine value) {
        return new JAXBElement<AD.StreetAddressLine>(_ADStreetAddressLine_QNAME, AD.StreetAddressLine.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AD.Direction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "direction", scope = AD.class)
    public JAXBElement<AD.Direction> createADDirection(AD.Direction value) {
        return new JAXBElement<AD.Direction>(_ADDirection_QNAME, AD.Direction.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AD.CensusTract }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "censusTract", scope = AD.class)
    public JAXBElement<AD.CensusTract> createADCensusTract(AD.CensusTract value) {
        return new JAXBElement<AD.CensusTract>(_ADCensusTract_QNAME, AD.CensusTract.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AD.PostalCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "postalCode", scope = AD.class)
    public JAXBElement<AD.PostalCode> createADPostalCode(AD.PostalCode value) {
        return new JAXBElement<AD.PostalCode>(_ADPostalCode_QNAME, AD.PostalCode.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AD.Delimiter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "delimiter", scope = AD.class)
    public JAXBElement<AD.Delimiter> createADDelimiter(AD.Delimiter value) {
        return new JAXBElement<AD.Delimiter>(_ADDelimiter_QNAME, AD.Delimiter.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SXCMTS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "validTime", scope = AD.class)
    public JAXBElement<SXCMTS> createADValidTime(SXCMTS value) {
        return new JAXBElement<SXCMTS>(_ADValidTime_QNAME, SXCMTS.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AD.County }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "county", scope = AD.class)
    public JAXBElement<AD.County> createADCounty(AD.County value) {
        return new JAXBElement<AD.County>(_ADCounty_QNAME, AD.County.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link INTInc }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "high", scope = IVLINT.class)
    public JAXBElement<INTInc> createIVLINTHigh(INTInc value) {
        return new JAXBElement<INTInc>(_IVLINTHigh_QNAME, INTInc.class, IVLINT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link INTInc }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "low", scope = IVLINT.class)
    public JAXBElement<INTInc> createIVLINTLow(INTInc value) {
        return new JAXBElement<INTInc>(_IVLINTLow_QNAME, INTInc.class, IVLINT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link INT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "center", scope = IVLINT.class)
    public JAXBElement<INT> createIVLINTCenter(INT value) {
        return new JAXBElement<INT>(_IVLINTCenter_QNAME, INT.class, IVLINT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "width", scope = IVLINT.class)
    public JAXBElement<PQ> createIVLINTWidth(PQ value) {
        return new JAXBElement<PQ>(_IVLINTWidth_QNAME, PQ.class, IVLINT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLTS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "validTime", scope = HXITPQ.class)
    public JAXBElement<IVLTS> createHXITPQValidTime(IVLTS value) {
        return new JAXBElement<IVLTS>(_ADValidTime_QNAME, IVLTS.class, HXITPQ.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PQR }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "translation", scope = HXITPQ.class)
    public JAXBElement<PQR> createHXITPQTranslation(PQR value) {
        return new JAXBElement<PQR>(_HXITPQTranslation_QNAME, PQR.class, HXITPQ.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TSInc }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "high", scope = IVLTS.class)
    public JAXBElement<TSInc> createIVLTSHigh(TSInc value) {
        return new JAXBElement<TSInc>(_IVLINTHigh_QNAME, TSInc.class, IVLTS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TSInc }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "low", scope = IVLTS.class)
    public JAXBElement<TSInc> createIVLTSLow(TSInc value) {
        return new JAXBElement<TSInc>(_IVLINTLow_QNAME, TSInc.class, IVLTS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "center", scope = IVLTS.class)
    public JAXBElement<TS> createIVLTSCenter(TS value) {
        return new JAXBElement<TS>(_IVLINTCenter_QNAME, TS.class, IVLTS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "width", scope = IVLTS.class)
    public JAXBElement<PQ> createIVLTSWidth(PQ value) {
        return new JAXBElement<PQ>(_IVLINTWidth_QNAME, PQ.class, IVLTS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PQInc }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "high", scope = IVLPQ.class)
    public JAXBElement<PQInc> createIVLPQHigh(PQInc value) {
        return new JAXBElement<PQInc>(_IVLINTHigh_QNAME, PQInc.class, IVLPQ.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PQInc }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "low", scope = IVLPQ.class)
    public JAXBElement<PQInc> createIVLPQLow(PQInc value) {
        return new JAXBElement<PQInc>(_IVLINTLow_QNAME, PQInc.class, IVLPQ.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "center", scope = IVLPQ.class)
    public JAXBElement<PQ> createIVLPQCenter(PQ value) {
        return new JAXBElement<PQ>(_IVLINTCenter_QNAME, PQ.class, IVLPQ.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "width", scope = IVLPQ.class)
    public JAXBElement<PQ> createIVLPQWidth(PQ value) {
        return new JAXBElement<PQ>(_IVLINTWidth_QNAME, PQ.class, IVLPQ.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PPDTS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "high", scope = IVLPPDTS.class)
    public JAXBElement<PPDTS> createIVLPPDTSHigh(PPDTS value) {
        return new JAXBElement<PPDTS>(_IVLINTHigh_QNAME, PPDTS.class, IVLPPDTS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLPPDTS.Low }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "low", scope = IVLPPDTS.class)
    public JAXBElement<IVLPPDTS.Low> createIVLPPDTSLow(IVLPPDTS.Low value) {
        return new JAXBElement<IVLPPDTS.Low>(_IVLINTLow_QNAME, IVLPPDTS.Low.class, IVLPPDTS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PPDTS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "center", scope = IVLPPDTS.class)
    public JAXBElement<PPDTS> createIVLPPDTSCenter(PPDTS value) {
        return new JAXBElement<PPDTS>(_IVLINTCenter_QNAME, PPDTS.class, IVLPPDTS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PPDPQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "width", scope = IVLPPDTS.class)
    public JAXBElement<PPDPQ> createIVLPPDTSWidth(PPDPQ value) {
        return new JAXBElement<PPDPQ>(_IVLINTWidth_QNAME, PPDPQ.class, IVLPPDTS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MOInc }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "high", scope = IVLMO.class)
    public JAXBElement<MOInc> createIVLMOHigh(MOInc value) {
        return new JAXBElement<MOInc>(_IVLINTHigh_QNAME, MOInc.class, IVLMO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MOInc }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "low", scope = IVLMO.class)
    public JAXBElement<MOInc> createIVLMOLow(MOInc value) {
        return new JAXBElement<MOInc>(_IVLINTLow_QNAME, MOInc.class, IVLMO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "center", scope = IVLMO.class)
    public JAXBElement<MO> createIVLMOCenter(MO value) {
        return new JAXBElement<MO>(_IVLINTCenter_QNAME, MO.class, IVLMO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "width", scope = IVLMO.class)
    public JAXBElement<PQ> createIVLMOWidth(PQ value) {
        return new JAXBElement<PQ>(_IVLINTWidth_QNAME, PQ.class, IVLMO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnSfx }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "suffix", scope = EN.class)
    public JAXBElement<EnSfx> createENSuffix(EnSfx value) {
        return new JAXBElement<EnSfx>(_ENSuffix_QNAME, EnSfx.class, EN.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnDel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "delimiter", scope = EN.class)
    public JAXBElement<EnDel> createENDelimiter(EnDel value) {
        return new JAXBElement<EnDel>(_ADDelimiter_QNAME, EnDel.class, EN.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLTS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "validTime", scope = EN.class)
    public JAXBElement<IVLTS> createENValidTime(IVLTS value) {
        return new JAXBElement<IVLTS>(_ADValidTime_QNAME, IVLTS.class, EN.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnPfx }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "prefix", scope = EN.class)
    public JAXBElement<EnPfx> createENPrefix(EnPfx value) {
        return new JAXBElement<EnPfx>(_ENPrefix_QNAME, EnPfx.class, EN.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnFam }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "family", scope = EN.class)
    public JAXBElement<EnFam> createENFamily(EnFam value) {
        return new JAXBElement<EnFam>(_ENFamily_QNAME, EnFam.class, EN.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnGiv }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "given", scope = EN.class)
    public JAXBElement<EnGiv> createENGiven(EnGiv value) {
        return new JAXBElement<EnGiv>(_ENGiven_QNAME, EnGiv.class, EN.class, value);
    }

}
