//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.09 at 10:59:16 AM EST 
//


package org.cvrgrid.hl7aecg.jaxb.beans;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ParticipationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ParticipationType">
 *   &lt;restriction base="{urn:hl7-org:v3}cs">
 *     &lt;enumeration value="ADM"/>
 *     &lt;enumeration value="ATND"/>
 *     &lt;enumeration value="DIS"/>
 *     &lt;enumeration value="ESC"/>
 *     &lt;enumeration value="REF"/>
 *     &lt;enumeration value="IND"/>
 *     &lt;enumeration value="BEN"/>
 *     &lt;enumeration value="COV"/>
 *     &lt;enumeration value="HLD"/>
 *     &lt;enumeration value="RCT"/>
 *     &lt;enumeration value="RCV"/>
 *     &lt;enumeration value="ENT"/>
 *     &lt;enumeration value="INF"/>
 *     &lt;enumeration value="NOT"/>
 *     &lt;enumeration value="PRCP"/>
 *     &lt;enumeration value="TRC"/>
 *     &lt;enumeration value="DIST"/>
 *     &lt;enumeration value="PPRF"/>
 *     &lt;enumeration value="DIR"/>
 *     &lt;enumeration value="CSM"/>
 *     &lt;enumeration value="TPA"/>
 *     &lt;enumeration value="DEV"/>
 *     &lt;enumeration value="NRD"/>
 *     &lt;enumeration value="RDV"/>
 *     &lt;enumeration value="BBY"/>
 *     &lt;enumeration value="DON"/>
 *     &lt;enumeration value="PRD"/>
 *     &lt;enumeration value="SBJ"/>
 *     &lt;enumeration value="LOC"/>
 *     &lt;enumeration value="DST"/>
 *     &lt;enumeration value="ELOC"/>
 *     &lt;enumeration value="ORG"/>
 *     &lt;enumeration value="RML"/>
 *     &lt;enumeration value="VIA"/>
 *     &lt;enumeration value="AUTHEN"/>
 *     &lt;enumeration value="LA"/>
 *     &lt;enumeration value="CON"/>
 *     &lt;enumeration value="AUT"/>
 *     &lt;enumeration value="PRF"/>
 *     &lt;enumeration value="SPRF"/>
 *     &lt;enumeration value="VRF"/>
 *     &lt;enumeration value="WIT"/>
 *     &lt;enumeration value="CST"/>
 *     &lt;enumeration value="RESP"/>
 *     &lt;enumeration value="SPC"/>
 *     &lt;enumeration value="RESPROV"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ParticipationType")
@XmlEnum
public enum ParticipationType {

    ADM,
    ATND,
    DIS,
    ESC,
    REF,
    IND,
    BEN,
    COV,
    HLD,
    RCT,
    RCV,
    ENT,
    INF,
    NOT,
    PRCP,
    TRC,
    DIST,
    PPRF,
    DIR,
    CSM,
    TPA,
    DEV,
    NRD,
    RDV,
    BBY,
    DON,
    PRD,
    SBJ,
    LOC,
    DST,
    ELOC,
    ORG,
    RML,
    VIA,
    AUTHEN,
    LA,
    CON,
    AUT,
    PRF,
    SPRF,
    VRF,
    WIT,
    CST,
    RESP,
    SPC,
    RESPROV;

    public String value() {
        return name();
    }

    public static ParticipationType fromValue(String v) {
        return valueOf(v);
    }

}
