//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.09 at 10:59:16 AM EST 
//


package org.cvrgrid.hl7aecg.jaxb.beans;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RoleClass.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RoleClass">
 *   &lt;restriction base="{urn:hl7-org:v3}cs">
 *     &lt;enumeration value="ROL"/>
 *     &lt;enumeration value="AGNT"/>
 *     &lt;enumeration value="CON"/>
 *     &lt;enumeration value="ECON"/>
 *     &lt;enumeration value="NOK"/>
 *     &lt;enumeration value="SGNOFF"/>
 *     &lt;enumeration value="GUARD"/>
 *     &lt;enumeration value="EMP"/>
 *     &lt;enumeration value="MIL"/>
 *     &lt;enumeration value="CIT"/>
 *     &lt;enumeration value="CRINV"/>
 *     &lt;enumeration value="CRSPNSR"/>
 *     &lt;enumeration value="GUAR"/>
 *     &lt;enumeration value="PAT"/>
 *     &lt;enumeration value="RESBJ"/>
 *     &lt;enumeration value="STD"/>
 *     &lt;enumeration value="PRS"/>
 *     &lt;enumeration value="DST"/>
 *     &lt;enumeration value="RET"/>
 *     &lt;enumeration value="MANU"/>
 *     &lt;enumeration value="THER"/>
 *     &lt;enumeration value="SDLOC"/>
 *     &lt;enumeration value="ISDLOC"/>
 *     &lt;enumeration value="ACCESS"/>
 *     &lt;enumeration value="BIRTHPL"/>
 *     &lt;enumeration value="EXPR"/>
 *     &lt;enumeration value="HLD"/>
 *     &lt;enumeration value="IDENT"/>
 *     &lt;enumeration value="MNT"/>
 *     &lt;enumeration value="OWN"/>
 *     &lt;enumeration value="RGPR"/>
 *     &lt;enumeration value="TERR"/>
 *     &lt;enumeration value="WRTE"/>
 *     &lt;enumeration value="GEN"/>
 *     &lt;enumeration value="GRIC"/>
 *     &lt;enumeration value="INST"/>
 *     &lt;enumeration value="SUBS"/>
 *     &lt;enumeration value="INGR"/>
 *     &lt;enumeration value="IACT"/>
 *     &lt;enumeration value="COLR"/>
 *     &lt;enumeration value="FLVR"/>
 *     &lt;enumeration value="PRSV"/>
 *     &lt;enumeration value="STBL"/>
 *     &lt;enumeration value="ACTI"/>
 *     &lt;enumeration value="ACTM"/>
 *     &lt;enumeration value="ADTV"/>
 *     &lt;enumeration value="BASE"/>
 *     &lt;enumeration value="LOCE"/>
 *     &lt;enumeration value="STOR"/>
 *     &lt;enumeration value="SPEC"/>
 *     &lt;enumeration value="ALQT"/>
 *     &lt;enumeration value="ISLT"/>
 *     &lt;enumeration value="CONT"/>
 *     &lt;enumeration value="MBR"/>
 *     &lt;enumeration value="PART"/>
 *     &lt;enumeration value="HLTHCHRT"/>
 *     &lt;enumeration value="COVPTY"/>
 *     &lt;enumeration value="POLHOLD"/>
 *     &lt;enumeration value="SPNSR"/>
 *     &lt;enumeration value="UNDWRT"/>
 *     &lt;enumeration value="PAYEE"/>
 *     &lt;enumeration value="PAYOR"/>
 *     &lt;enumeration value="LIC"/>
 *     &lt;enumeration value="DSDLOC"/>
 *     &lt;enumeration value="NOT"/>
 *     &lt;enumeration value="PROV"/>
 *     &lt;enumeration value="ASSIGNED"/>
 *     &lt;enumeration value="QUAL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RoleClass")
@XmlEnum
public enum RoleClass {

    ROL,
    AGNT,
    CON,
    ECON,
    NOK,
    SGNOFF,
    GUARD,
    EMP,
    MIL,
    CIT,
    CRINV,
    CRSPNSR,
    GUAR,
    PAT,
    RESBJ,
    STD,
    PRS,
    DST,
    RET,
    MANU,
    THER,
    SDLOC,
    ISDLOC,
    ACCESS,
    BIRTHPL,
    EXPR,
    HLD,
    IDENT,
    MNT,
    OWN,
    RGPR,
    TERR,
    WRTE,
    GEN,
    GRIC,
    INST,
    SUBS,
    INGR,
    IACT,
    COLR,
    FLVR,
    PRSV,
    STBL,
    ACTI,
    ACTM,
    ADTV,
    BASE,
    LOCE,
    STOR,
    SPEC,
    ALQT,
    ISLT,
    CONT,
    MBR,
    PART,
    HLTHCHRT,
    COVPTY,
    POLHOLD,
    SPNSR,
    UNDWRT,
    PAYEE,
    PAYOR,
    LIC,
    DSDLOC,
    NOT,
    PROV,
    ASSIGNED,
    QUAL;

    public String value() {
        return name();
    }

    public static RoleClass fromValue(String v) {
        return valueOf(v);
    }

}
