//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.09 at 10:59:16 AM EST 
//


package org.cvrgrid.hl7aecg.jaxb.beans;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RoleClassPartitive.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RoleClassPartitive">
 *   &lt;restriction base="{urn:hl7-org:v3}RoleClass">
 *     &lt;enumeration value="INGR"/>
 *     &lt;enumeration value="IACT"/>
 *     &lt;enumeration value="COLR"/>
 *     &lt;enumeration value="FLVR"/>
 *     &lt;enumeration value="PRSV"/>
 *     &lt;enumeration value="STBL"/>
 *     &lt;enumeration value="ACTI"/>
 *     &lt;enumeration value="ACTM"/>
 *     &lt;enumeration value="ADTV"/>
 *     &lt;enumeration value="BASE"/>
 *     &lt;enumeration value="LOCE"/>
 *     &lt;enumeration value="STOR"/>
 *     &lt;enumeration value="SPEC"/>
 *     &lt;enumeration value="ALQT"/>
 *     &lt;enumeration value="ISLT"/>
 *     &lt;enumeration value="CONT"/>
 *     &lt;enumeration value="MBR"/>
 *     &lt;enumeration value="PART"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RoleClassPartitive")
@XmlEnum(RoleClass.class)
public enum RoleClassPartitive {

    INGR,
    IACT,
    COLR,
    FLVR,
    PRSV,
    STBL,
    ACTI,
    ACTM,
    ADTV,
    BASE,
    LOCE,
    STOR,
    SPEC,
    ALQT,
    ISLT,
    CONT,
    MBR,
    PART;

    public String value() {
        return name();
    }

    public static RoleClassPartitive fromValue(String v) {
        return valueOf(v);
    }

}
