//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.09 at 10:59:16 AM EST 
//


package org.cvrgrid.hl7aecg.jaxb.beans;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RoleClassAgent.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RoleClassAgent">
 *   &lt;restriction base="{urn:hl7-org:v3}RoleClassRelationshipFormal">
 *     &lt;enumeration value="ASSIGNED"/>
 *     &lt;enumeration value="CON"/>
 *     &lt;enumeration value="ECON"/>
 *     &lt;enumeration value="NOK"/>
 *     &lt;enumeration value="SGNOFF"/>
 *     &lt;enumeration value="GUARD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RoleClassAgent")
@XmlEnum(RoleClassRelationshipFormal.class)
public enum RoleClassAgent {

    ASSIGNED,
    CON,
    ECON,
    NOK,
    SGNOFF,
    GUARD;

    public String value() {
        return name();
    }

    public static RoleClassAgent fromValue(String v) {
        return valueOf(v);
    }

}
