//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.09 at 10:59:16 AM EST 
//


package org.cvrgrid.hl7aecg.jaxb.beans;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TableRowGroupType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TableRowGroupType">
 *   &lt;restriction base="{urn:hl7-org:v3}DocumentTableRowGroup">
 *     &lt;enumeration value="tbody"/>
 *     &lt;enumeration value="tfoot"/>
 *     &lt;enumeration value="thead"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TableRowGroupType")
@XmlEnum(DocumentTableRowGroup.class)
public enum TableRowGroupType {

    @XmlEnumValue("tbody")
    TBODY(DocumentTableRowGroup.TBODY),
    @XmlEnumValue("tfoot")
    TFOOT(DocumentTableRowGroup.TFOOT),
    @XmlEnumValue("thead")
    THEAD(DocumentTableRowGroup.THEAD);
    private final DocumentTableRowGroup value;

    TableRowGroupType(DocumentTableRowGroup v) {
        value = v;
    }

    public DocumentTableRowGroup value() {
        return value;
    }

    public static TableRowGroupType fromValue(DocumentTableRowGroup v) {
        for (TableRowGroupType c: TableRowGroupType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
