//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.09 at 10:59:16 AM EST 
//


package org.cvrgrid.hl7aecg.jaxb.beans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			A telephone number (voice or fax), e-mail address, or other locator
 * 			for a resource (information or service) mediated by telecommunication
 * 			equipment. The address is specified as a Universal Resource Locator
 * 			(URL) qualified by time specification and use codes that help in
 * 			deciding which address to use for a given time and purpose.
 * 			
 * 
 * <p>Java class for TEL complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TEL">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:v3}URL">
 *       &lt;sequence>
 *         &lt;element name="validTime" type="{urn:hl7-org:v3}SXCM_TS" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="use" type="{urn:hl7-org:v3}set_cs_TelecommunicationAddressUse" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TEL", propOrder = {
    "validTime"
})
public class TEL
    extends URL
{

    protected List<SXCMTS> validTime;
    @XmlAttribute(name = "use")
    protected List<CsTelecommunicationAddressUse> use;

    /**
     * Gets the value of the validTime property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the validTime property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValidTime().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SXCMTS }
     * 
     * 
     */
    public List<SXCMTS> getValidTime() {
        if (validTime == null) {
            validTime = new ArrayList<SXCMTS>();
        }
        return this.validTime;
    }

    /**
     * Gets the value of the use property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the use property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CsTelecommunicationAddressUse }
     * 
     * 
     */
    public List<CsTelecommunicationAddressUse> getUse() {
        if (use == null) {
            use = new ArrayList<CsTelecommunicationAddressUse>();
        }
        return this.use;
    }

}
